### ISSUE TITLE
Get asset utxo given a liquid adddress and asset hash 

### ISSUE THREAD

**Issue by tiero** [Blockstream/esplora#100]
There is a way to crawl unblinded assets utxo given the asset hash and the output address? Or even better having all the assets for that address.

For instance, using an asset issuance tx hash via `/tx/<txid>` there is no mention (asset == null) of the asset hash both on the `vin` abd `vout` field.

**Comment by shesek** [comment]
> For instance, using an asset issuance tx hash via `/tx/<txid>` there is no mention (asset == null) of the asset hash both on the `vin` and `vout` field.

Issuance transactions works a bit differently. You wouldn't see the newly issued asset id in the `asset` of the input (which is the asset of the prevout spent by the input), nor in any of the outputs (assuming you're sending the tokens to a blinded address, the `asset` would be `null`).

Getting the issued asset of an issuance transaction requires computing it from the asset entropy and the prevout being spent. I have a [work-in-progress branch](https://github.com/shesek/electrs/commits/201905-asset-index) where [this was implemented](https://github.com/shesek/electrs/commit/183571ecb266d372ce419ea29ffc00d5f52ca663), among a bunch of other asset-related features. Should go live soon-ish :)

For non-issuance transactions, you should be seeing the correct `asset` on unblinded outputs and their spends when requesting `/tx/<txid>`.

> Or even better having all the assets for that address.

`/address/<address>/utxo` should give you a list of all unspent outputs and their asset ids (for the non-blinded ones), but I'll need to double-check to verify this (the utxo endpoint gets its data from the txo index directly, which handles assets a bit differently than the tx store used for `/tx/<txid>`).

**Comment by shesek** [comment]
> but I'll need to double-check to verify this

I just checked, asset information is apparently not available in the utxo endpoint (I suspected this for some reason...). Created #101 to keep track of that.

**Comment by shesek** [comment]
@tiero #101 has been resolved, is there anything else you'd like to see gets implemented?

**Comment by tiero** [comment]
Awesome! Will test this out shortly!
