### ISSUE TITLE
error in distance from tip for unconfirmed transaction

### ISSUE THREAD

**Issue by dooglus** [Blockstream/esplora#102]
Here's an unconfirmed transaction paying ~42 sat/vB, and a screenshot of [Johoe's mempool stats site](https://jochen-hoenicke.de/queue/#1,2h) showing that there are around 2 vMB above it in the pool. The explorer claims it is 0.0 vMB from the tip, but that it will take 144 blocks to confirm:

![Screenshot - 19-06-22 - 01:02:57 PM](https://user-images.githubusercontent.com/573356/59968436-d056fd80-94ee-11e9-883b-c2d90cc8bd82.png)

I understand that it's next to impossible to estimate the ETA without a crystal ball, but the depth in the pool should be calculable pretty easily.

**Comment by dooglus** [comment]
I checked 5 more low-fee unconfirmed transactions at random and all 5 of them were showing "in 144 blocks (0.00 vMB from tip)" as the ETA.

**Comment by shesek** [comment]
It's a known bug that was recently fixed by https://github.com/Blockstream/electrs/commit/baee77b68ac74d1f2acf3b4e260e22f0ed75958c, which will go live with the next deployment. I'll try to make sure that happens soon. Cheers and thanks for the bug report!
