### ISSUE TITLE
Use newlines for witness stack elements

### ISSUE THREAD

**Issue by Sjors** [Blockstream/esplora#113]
It's quite difficult to notice an empty stack element currently. Take for example [a08e6620d21b8f451c63dfe8d0164f0ba1b2dc781ea163c7990634747b57282c](https://www.blockstream.info/tx/a08e6620d21b8f451c63dfe8d0164f0ba1b2dc781ea163c7990634747b57282c?expand).

In Bitcoin Core:
<img width="1248" alt="core" src="https://user-images.githubusercontent.com/10217/61048384-91bfaf00-a3d9-11e9-8019-08b1fff32cfa.png">

In the explorer:
<img width="414" alt="explorer" src="https://user-images.githubusercontent.com/10217/61048383-91271880-a3d9-11e9-8ce5-977ea83d8e11.png">

**Comment by shesek** [comment]
How about using something like *<empty>* to indicate empty stack elements instead?

**Comment by shesek** [comment]
Implemented in https://github.com/Blockstream/esplora/commit/735c21423c097abc3dea63ee111b88366191163e.

Thanks for the suggestion!
