### ISSUE TITLE
Liquid explorer requires (several) refresh to correctly display Asset info from Registry

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [Blockstream/esplora#114]
Both transactions and assets require (a few) refresh(es) for them to be displayed together with the asset metadata fetched from the Registry (this is especially confusing with amounts if a non-null precision is specified on the Registry).

Tx ref: https://blockstream.info/liquid/tx/4de2f4c4f4a5422969921a1960f154d0965dfe79454a3053a60ce95cdc63e553?expand

Asset ref: https://blockstream.info/liquid/asset/d9f6bb516c9f3ab16bed3f3662ae018573ee6b00130f2347a4b735d8e7c4c396

![Screen Shot 2019-07-16 at 11 06 23](https://user-images.githubusercontent.com/22540533/61281900-b42b4100-a7ba-11e9-8036-7d148b8889e5.png)
![Screen Shot 2019-07-16 at 11 12 57](https://user-images.githubusercontent.com/22540533/61281906-b7bec800-a7ba-11e9-99c2-c977d77938d2.png)

**Comment by greenaddress** [comment]
fixed now
