### ISSUE TITLE
UI improvements for the asset view on Liquid

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [Blockstream/esplora#115]
I'm taking an existing asset on the registry as an example https://blockstream.info/liquid/asset/d9f6bb516c9f3ab16bed3f3662ae018573ee6b00130f2347a4b735d8e7c4c396

- [x] For consistency with Green, a few fields would benefit if they are called the same at UI level, on the Explorer like in Green:
- s/"Linked domain"/"Issuer Domain"/
- s/"Description"/"Name"/
- s/"Decimal places"/"Precision - decimal places"/

- [x] Would be useful to add in this tableview also the "Asset ID" field and to display the 64char HEX (even if it's already displayed above, it's a useful repetition as it's the most important identifier of the asset).

- [x] The ideal order of the info displayed in the tableview would be:

- Asset ID
- Name
- Precision - decimal places
- Ticker
- Issuer domain
- Issuance transaction
- Included in Block
- Number of issuances
- Number of issuances (unconfirmed)
- Issued amount
- Issued amount (unconfirmed)
- Burned amount
- Burned amount (unconfirmed)
- Reissuance tokens created
- Reissuance tokens burned
- Reissuance tokens burned (unconfirmed)
- Re-issuable
- Contract hash
- Contract JSON

![Screen Shot 2019-07-16 at 18 15 19](https://user-images.githubusercontent.com/22540533/61311062-da220700-a7f5-11e9-8344-6d977dac32c8.png)

**Comment by shesek** [comment]
Implemented the first two requests. As for the ordering, there are a few more fields that are only shown when relevant. Could you provide the ordering including all of them? You can see the full list [here](https://github.com/Blockstream/esplora/blob/735c21423c097abc3dea63ee111b88366191163e/client/src/views/asset.js#L50-L147).

**Comment by alessandro-saglimbeni** [comment]
> As for the ordering, there are a few more fields that are only shown when relevant. Could you provide the ordering including all of them? 

I've edited the issue accordingly

**Comment by shesek** [comment]
Re-ordered in https://github.com/Blockstream/esplora/commit/37d8c0c7086884cd3173535c283bd53edbd02f64.
