### ISSUE TITLE
can this project used for my coin(edit by bitcoin v0.16)

### ISSUE THREAD

**Issue by kolvin2016** [Blockstream/esplora#122]
i have changed bitcoin some source code for version 0.16.
changed port , pchMessageStart, base58Prefixes
can used for it?

**Comment by shesek** [comment]
You may use this source code under the terms of the [MIT license](https://github.com/Blockstream/esplora/blob/master/LICENSE). It would probably require adjustments to work with your altcoin. This is not something that I can provide support for, but you can feel free to do this. Good luck.
