### ISSUE TITLE
get error when npm install in client folder 

### ISSUE THREAD

**Issue by kolvin2016** [Blockstream/esplora#123]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
gyp ERR! stack     at Object.userInfo (os.js:249:11)
gyp ERR! stack     at eaccesFallback (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:374:92)
gyp ERR! stack     at /usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:83:11
gyp ERR! stack     at callback (/usr/local/node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:289:20)
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/esplora/client/node_modules/canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN esplora-client@0.1.0 No description
npm WARN esplora-client@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-19T15_36_37_957Z-debug.log

**Comment by shesek** [comment]
Which OS are you using?

One possible workaround is to use the Docker image. (but of course, it would be better to get this working :))

**Comment by alvarosilvac** [comment]
> gyp ERR! UNCAUGHT EXCEPTION
> gyp ERR! stack SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
> gyp ERR! stack at Object.userInfo (os.js:249:11)
> gyp ERR! stack at eaccesFallback (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:374:92)
> gyp ERR! stack at /usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:83:11
> gyp ERR! stack at callback (/usr/local/node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:289:20)
> gyp ERR! stack at FSReqWrap.oncomplete (fs.js:154:21)
> gyp ERR! System Linux 3.10.0-862.el7.x86_64
> gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/esplora/client/node_modules/canvas
> gyp ERR! node -v v10.15.0
> gyp ERR! node-gyp -v v5.0.2
> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR! https://github.com/nodejs/node-gyp/issues
> npm WARN esplora-client@0.1.0 No description
> npm WARN esplora-client@0.1.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 7
> npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
> npm ERR! Exit status 7
> npm ERR!
> npm ERR! Failed at the canvas@1.6.13 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-07-19T15_36_37_957Z-debug.log

```
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

Did the trick for me

**Comment by shesek** [comment]
Esplora no longer depends on canvas, which should make the installation more straightforward and male these native module issues go away.
