### ISSUE TITLE
Addresses with a large number of transactions aren't currently supported

### ISSUE THREAD

**Issue by andronoob** [Blockstream/esplora#13]
For example: https://blockstream.info/address/1VayNert3x1KzbpzMGt2qdqrAThiRovi8

**Comment by greenaddress** [comment]
@andronoob thanks! There's a PR here https://github.com/Blockstream/electrs/pull/5 with a new schema design we plan to use

no eta yet but on it!

**Comment by greenaddress** [comment]
this has been fixed in master and deployed. thanks! Closing
