### ISSUE TITLE
Empty transaction crash

### ISSUE THREAD

**Issue by kprimice** [Blockstream/esplora#131]
I tried to look at 2 txs: 

`3c575fb4b715900d2e10f12ab4d5aad5941f46a90168fb33eb575fc1ade2b260`
`2f2442f68e38b980a6c4cec21e71851b0d8a5847d85208331a27321a9967bbd6`

However they make the explorer crash (on blockstream.info).

I suspect its because of their 0 BTC output.

**Comment by greenaddress** [comment]
@kprimice thanks, looks like the js frontend doesn't handle those well - will work on a fix.

**Comment by greenaddress** [comment]
@kprimice it has been fixed, thank you again for the report. It will be going live in the next deployment

**Comment by greenaddress** [comment]
@kprimice this has been deployed and works correctly now. Closing!
