### ISSUE TITLE
OP_CHECKLOCKTIMEVERIFY rendered as OP_NOP2

### ISSUE THREAD

**Issue by araspitzu** [Blockstream/esplora#132]
The `/tx` page renders OP_CHECKLOCKTIMEVERIFY as OP_NOP2, related issue #98

**Comment by greenaddress** [comment]
@araspitzu IIRC this was solved upstream and we deployed an update today so it may be fixed, will test and get back - thanks!

**Comment by araspitzu** [comment]
Not sure if blockstream.info has received the update but [this](https://blockstream.info/testnet/tx/7990d75a600d6cfb4099e5ba5661377f6ed95a127ae03bb1909a82249130f9c4?input:0&expand) is still broken.

**Comment by stevenroose** [comment]
Perhaps you should clear your browser cache? I see it rendered like this:
![screenshot-2019-08-21-18-40-55](https://user-images.githubusercontent.com/853468/63454716-402c2a80-c443-11e9-9c82-45d76094f1cd.png)

**Comment by araspitzu** [comment]
That was it - thanks for the work!
