### ISSUE TITLE
Is it possible  to directly query the databse?

### ISSUE THREAD

**Issue by SHlNOBI** [Blockstream/esplora#136]
I haven't yet tried this awesome project. I would  like to know whether its possible to directly query the databse  rather than API.

**Comment by greenaddress** [comment]
@SHlNOBI The db is rocksdb, which has a number of bindings available (we use rust) - you can query that db with ad-hoc code - you can find more information here https://rocksdb.org

**Comment by SHlNOBI** [comment]
Thank you for the info.
