### ISSUE TITLE
P2PK is not currently supported, leading to inaccurate address balance

### ISSUE THREAD

**Issue by andronoob** [Blockstream/esplora#14]
Example: https://blockstream.info/address/17iyRRXBHJKbv5DKPPkttWewm3CHdNPGQd

```
scantxoutset "start" "[\"combo(041ada81ea00c11098d2f52c20d5aa9f5ba13f9b583fda66f2a478dd7d95a7ab615159d98b63df2e6f3ecb3ef9eda138e4587e7afd31e7f434cbb6837e17feb0c5)\"]"
```
```
{
  "success": true,
  "searched_items": 50244201,
  "unspents": [
    {
      "txid": "540a7e54fd64478554519f1b2d643ecc888c5030631487f9cfc530b71d281309",
      "vout": 0,
      "scriptPubKey": "41041ada81ea00c11098d2f52c20d5aa9f5ba13f9b583fda66f2a478dd7d95a7ab615159d98b63df2e6f3ecb3ef9eda138e4587e7afd31e7f434cbb6837e17feb0c5ac",
      "amount": 50.00000000,
      "height": 50
    },
    {
      "txid": "8efb0be559ea251459184beca257fb36746a6c7464098b1bed2d12bb1383713b",
      "vout": 0,
      "scriptPubKey": "76a91449c0e836a0bb1e176097e6408efe6cb4c11a98f588ac",
      "amount": 0.00100000,
      "height": 410333
    }
  ],
  "total_amount": 50.00100000
}
```

**Comment by greenaddress** [comment]
I think it is already correct behavior?

if you search by address I'd only expect p2pkh - you don't even know the public key of p2pk

**Comment by andronoob** [comment]
@greenaddress 
A lot of ancient transactions have P2PK output(s), including Satoshi's genesis coinbase transaction.

**Comment by greenaddress** [comment]
The explorer supports P2PK if you look up a transaction and you can highlight an output by appending to a URL #output:0 or whatever index the output is at.

Are you suggesting we should add search by public key or script pub key perhaps? because search by address (p2pkh or p2sh or bech32) shouldn't include p2pk IMHO

**Comment by andronoob** [comment]
@greenaddress 
> The explorer supports P2PK if you look up a transaction and you can highlight an output by appending to a URL #output:0 or whatever index the output is at.

It seems that almost all block explorers except blockstream.info would show P2PK outputs as common Base58 encoded P2PKH bitcoin addresses like 17iyRRXBHJKbv5DKPPkttWewm3CHdNPGQd.
The decoderawtransaction RPC call provided by Bitcoin Core also does the same thing:
```
decoderawtransaction 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0704ffff001d013fffffffff0100f2052a010000004341041ada81ea00c11098d2f52c20d5aa9f5ba13f9b583fda66f2a478dd7d95a7ab615159d98b63df2e6f3ecb3ef9eda138e4587e7afd31e7f434cbb6837e17feb0c5ac00000000
```
```
{
  "txid": "540a7e54fd64478554519f1b2d643ecc888c5030631487f9cfc530b71d281309",
  "hash": "540a7e54fd64478554519f1b2d643ecc888c5030631487f9cfc530b71d281309",
  "version": 1,
  "size": 134,
  "vsize": 134,
  "weight": 536,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "04ffff001d013f",
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 50.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "041ada81ea00c11098d2f52c20d5aa9f5ba13f9b583fda66f2a478dd7d95a7ab615159d98b63df2e6f3ecb3ef9eda138e4587e7afd31e7f434cbb6837e17feb0c5 OP_CHECKSIG",
        "hex": "41041ada81ea00c11098d2f52c20d5aa9f5ba13f9b583fda66f2a478dd7d95a7ab615159d98b63df2e6f3ecb3ef9eda138e4587e7afd31e7f434cbb6837e17feb0c5ac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "17iyRRXBHJKbv5DKPPkttWewm3CHdNPGQd"
        ]
      }
    }
  ]
}
```

> 
> Are you suggesting we should add search by public key or script pub key perhaps? because search by address (p2pkh or p2sh or bech32) shouldn't include p2pk IMHO

Not really, but this would be a really great feature IMHO.

**Comment by greenaddress** [comment]
> It seems that almost all block explorers except blockstream.info would show P2PK outputs as common Base58 encoded P2PKH bitcoin addresses like 17iyRRXBHJKbv5DKPPkttWewm3CHdNPGQd.

I understand but that seems a bug to me not a feature. 

> Are you suggesting we should add search by public key or script pub key perhaps? because search by address (p2pkh or p2sh or bech32) shouldn't include p2pk IMHO

Search by p2pk or scriptPubKey seems a decent feature to have, I added it to the list, see https://github.com/Blockstream/esplora/issues/15

**Comment by greenaddress** [comment]
Closing, using #15 to keep track of search by scriptpubkey/scripthash
