### ISSUE TITLE
Blockstream.info as json?

### ISSUE THREAD

**Issue by zoegod911** [Blockstream/esplora#140]
curious if I can make an request and receive the data as JSON.

ex: https://blockstream.info/testnet/address/mfskMRWntcPYdDgTJRJdwzdKiiHJikfvH4 (.json)

is this possible?

**Comment by shesek** [comment]
Yes, https://blockstream.info/testnet/api/address/mfskMRWntcPYdDgTJRJdwzdKiiHJikfvH4

Also see https://github.com/Blockstream/esplora/blob/master/API.md
