### ISSUE TITLE
Allow utxos search for short id

### ISSUE THREAD

**Issue by inaltoasinistra** [Blockstream/esplora#141]
Hello,
it would be useful to search utxos for short representation, the same used in Lightning Network.
For example, the 571954:2518:0 or 571954x2518x0 searches will be redirected [here](
https://blockstream.info/tx/d98fabc74e31ff13627e4f7720c3475e1081af99880a8534ae5e73eec4e87e9b?output:0)

**Comment by shesek** [comment]
That would be a pretty neat feature, thanks for the suggestion!

**Comment by shesek** [comment]
Implemented in https://github.com/Blockstream/electrs/commit/a786af56bd4f1512fef2207c238b32dc240c50d9 and https://github.com/Blockstream/esplora/commit/a2d1447549034523e8d3be3bdbd872dc235b94b2, should go live with the next deployment. Cheers.
