### ISSUE TITLE
PRECISION - DECIMAL PLACES

### ISSUE THREAD

**Issue by lbtil** [Blockstream/esplora#145]
Asset issued with precision 2, but on the explorer show 0 this is the image from register_asset.sh generated from the contract. 
{"asset_id":"aa775044c32a7df391902b3659f46dfe004ccb2644ce2ddc7dba31e889391caf","contract":{"entity":{"domain":"amole.org"},"issuer_pubkey":"03c5f0236f8f0b865d961ea22817621a3f645b39d1a38107255a74ec93b249f21b","name":"Ethiopian, Birr","precision":2,"ticker":"ETB","version":0},"issuance_txin":{"txid":"421dd5195c9f36bd56a79e3b0581620b11804ec9fbc9d03b36102c27781536c8","vin":0},"issuance_prevout":{"txid":"7ead93672f90b8eb6ccdc73ffe0cf0e1381023bd72ecdcbc73a33e9e6e9fcc1f","vout":0},"name":"Ethiopian, Birr","ticker":"ETB","precision":2,"entity":{"domain":"amole.org"}},

and this is what it show on asset explorer. 
https://blockstream.info/liquid/asset/aa775044c32a7df391902b3659f46dfe004ccb2644ce2ddc7dba31e889391caf

**Comment by shesek** [comment]
I see that this now shows properly with a precision of two, probably just took some time for the explorer to update.
