### ISSUE TITLE
Esplora HTTP API endpoint /asset/asset_id does not exist

### ISSUE THREAD

**Issue by lorenzodisidoro** [Blockstream/esplora#151]
I'm using docker image of esplora API locally to retrive some informations about transactions, asset, ...
After  issuing my assets I used [/asset/:assed_id](https://github.com/Blockstream/esplora/blob/master/API.md#issued-assets-elementsliquid-only) but the response was 
```sh
endpoint does not exist "/asset/2dcf5a8834645654911964ec3602426fd3b9b4017554d3f9c19403e7fc1411d3"
```

The other endpoints work, am I doing something wrong?

**Comment by lorenzodisidoro** [comment]
> Did you prefix the API URL with `https://blockstream.info/liquid/api/`?
> 
> This seems to work: https://blockstream.info/liquid/api/asset/ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2

I running esplora API locally but yes, I added the prefix API 
`http://localhost:<esplora_port>/liquid/api/`

**Comment by shesek** [comment]
If you're running electrs locally then you should be accessing the electrs http port directly (and not esplora's) and wouldn't have the `/liquid/` or the `/api/` prefix. The default port for electrs is 3000, so this should be accessible at:

http://localhost:3000/asset/ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2

**Comment by shesek** [comment]
> If you're running electrs locally then you should ...

Well actually, this depends: are you using the docker image or running things manually?

**Comment by lorenzodisidoro** [comment]
I issued a new asset and tried `GET /asset/:asset_id` but the error is the same.

> Well actually, this depends: are you using the docker image or running things manually?

I'm using docker image and Electrs commit is `a6fc0b81fa805f565f6043529fe03632dff9e531 `

**Comment by shesek** [comment]
Your electrs commit is quite old, the current master of esplora points to a much newer one. Can you try running the latest esplora docker image?

**Comment by lorenzodisidoro** [comment]
You are right! Using the latest version of electrs the endpoint work 🎉 
Thanks @shesek

**Comment by shesek** [comment]
Hooray! :)
