### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined when attempting Pre-rendering server

### ISSUE THREAD

**Issue by pedromvpg** [Blockstream/esplora#152]
Found this block when trying to run the `npm run prerender-server` command.
Am I missing something?
![Screen Shot 2019-10-28 at 9 52 32 PM](https://user-images.githubusercontent.com/807505/67731884-0726ae00-f9d0-11e9-8c74-2f6001ba9128.png)

**Comment by shesek** [comment]
You have to provide the `API_URL` environment variable with the base URL of the Electrs HTTP REST API, as well as `STATIC_ROOT` with the base URL where the static assets (css/js/images) are available (you'll need to set this up separately, either with a standalone http server like nginx that points directly to the static assets directory, or using (the inefficient and not recommended for production use) `npm run dev-server`).

For example, to run this against the blockstream.info API and static assets, run:

```
$ export API_URL=http://blockstream.info/api/
$ export STATIC_ROOT=http://blockstream.info/
$ npm run prerender-server
```

Or if you have electrs and the dev-server running locally on the default ports:

```
$ export API_URL=http://localhost:3000/
$ export STATIC_ROOT=http://localhost:5000/
$ npm run prerender-server
```

Good luck, let me know if you're still having issues.

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
