### ISSUE TITLE
No resource for L-BTC in asset registry liquid/asset/<id>

### ISSUE THREAD

**Issue by philippem** [Blockstream/esplora#154]
Liquid Bitcoin, L-BTC is listed in the asset registry at
https://blockstream.info/liquid/assets/

but the links in that html page refer to the nonexistent resource 

https://blockstream.info/liquid/asset/6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d

L-BTC is different than other assets, but there is an expectation that the page refer to existing resources.

**Comment by shesek** [comment]
This was implemented recently, but still didn't get deployed on blockstream.info. Should go live with the next update.
