### ISSUE TITLE
Support upper case bech32

### ISSUE THREAD

**Issue by RCasatta** [Blockstream/esplora#161]
At the moment it looks if I search an uppercase bech32 address nothing is found.

Since the BIP specify that the encoding should be uppercase for qrcodes, so the encoding could be alphanumeric and the resulting qr code simpler, it could be common to have bech32 address in uppercase.

So I think the explorer should support searching for uppercase bech32 address

**Comment by shesek** [comment]
Implemented in 147993628d580e628cdc80b1af37e7b98f563199. Thanks for the heads up!
