### ISSUE TITLE
Feature request: Show difficulty for blocks

### ISSUE THREAD

**Issue by nitramiz** [Blockstream/esplora#167]
It'd be great if the difficulty was shown on the `blockstream.info/block/sha` page. What brought it to @niftynei's and my attention was the last "[blockstorm](https://medium.com/radartech/bitcoin-testnet3-epoch-723-blockstorm-bebb70b9501f)" on testnet.

The second request would be to have the search bar show up when you get to a "No results found" page. There's already an issue opened for this #63.

**Comment by shesek** [comment]
Added to the API in https://github.com/Blockstream/electrs/commit/9aa3f75656397826949eb2d1aca083c08ef67edc, but still not displayed in the UI.

**Comment by shesek** [comment]
https://github.com/Blockstream/esplora/commit/6b5b6083b7dafec07a441785454feab0d29924ea adds the block difficulty to the UI, under the block's "advanced details".
