### ISSUE TITLE
Suggestion: Clearer Date Format

### ISSUE THREAD

**Issue by MarioGibney** [Blockstream/esplora#174]
The current date is displayed as:

MM/DD/YYYY

This isn't very clear, since January 2, 2020 can easily be misread as February 1, 2020, and vice versa:

01/02/2020
02/01/2020

The above format isn't common outside the US, and there are other clearer formats that could be used. For example:

YYYY-MMM-DD
2020-Jan-02

or:

DD/MMM/YYY
02-Jan-2020

You can see in this screenshot how it currently looks ambiguous:

![image](https://user-images.githubusercontent.com/22239865/74785626-90077500-525f-11ea-9ff3-67c6e40c6cc5.png)

**Comment by shesek** [comment]
The date format is set according to the display language, which is set by default according to the user's browser settings.

But while this makes sense for some languages, this is definitely not ideal for English as there are many non-US users that would prefer an English interface but won't be accustomed to the MM/DD/YYYY date format.

I guess that we could always use the `YYYY-MM-DD` format and just ignore the locale? @greenaddress thoughts?

**Comment by shesek** [comment]
The date format was changed to `YYYY-MM-DD HH:MM:SS GMT+-N` in https://github.com/Blockstream/esplora/commit/651a453b89f4c0217a339dd92766865d9594cd7f.
