### ISSUE TITLE
Blank page when Javascript is disabled.

### ISSUE THREAD

**Issue by grubles** [Blockstream/esplora#18]
When viewing Blockstream.info with Javascript disabled (ie. via Tor Browser), only a blank page is presented.

**Comment by greenaddress** [comment]
Duplicate of https://github.com/Blockstream/esplora/issues/9

**Comment by shesek** [comment]
Not necessarily a duplicate of #9, even just displaying a "JavaScript is required" message would be an improvement over a blank page.

**Comment by adiack** [comment]
Just as a side note you will also get a blank page if you set API_URL to localhost while not running locally.. to get it to work I had to set API_URL=<external_IP:5000>
