### ISSUE TITLE
Esplora is currently unavailable, please try again later

### ISSUE THREAD

**Issue by cloakedch** [Blockstream/esplora#183]
I have spun up a new docker instance of blockstream/esplora and I get the above message when I try to access the frontend. Using the browser's (chrome) developers console in the network tab I could see that a request to `<my-ip>:8080/api/blocks/` failed with 502 Bad Gateway.

I ran the docker container like described on the github page under "How to run the explorer for Bitcoin mainnet". According to the logs, the docker container has finished synchronizing the blockchain blocks (up to the current time) within a few hours. I have also already re-created the container, but no luck.

What is the source of my problem?

**Comment by shesek** [comment]
Its possible that bitcoind finished syncing, but electrs still didn't. Were you able to get this working since posting the issue?

**Comment by cloakedch** [comment]
No. It's still not working.
The containers are idle, the logs don't show anything suspicious. I have tried this under two different machines:
- x64 with 8CPUs, 16GB RAM
- x64 with 48 CPUs, 256GB RAM

Exactely the same behaviour.

I have also purged all files and retried the same steps on both machines multiple times, without success.

**Comment by shesek** [comment]
Are you able to see the logs produced by the electrs daemon? Does it report any progress in the indexing process?

**Comment by cloakedch** [comment]
I have updated the git repository to todays commit and re-ran a new instance.
It seems to be working fine now.
Looking through some older github issues from other users indicate that there was an issue with _new_ instances started in the past weeks?

Anyway, glad it's working now.

**Comment by cloakedch** [comment]
Update:
I have setup a new instance using the commit from Mar 26, 2020. With this code, it seems to be running fine. Vertification and compaction finished within 24 hours.

**Comment by cloakedch** [comment]
Suggestion:

If you follow the readme and build the docker container inside the cloned repository (`docker build -t esplora`), you should add `data_bitcoin_mainnet` to the .dockerignore file, so that when doing a `git pull` later, it will not push the whole data folder into the docker context.

**Comment by shesek** [comment]
Thanks for the suggestion @cloakedch! Added in https://github.com/Blockstream/esplora/commit/57b267b9f645fae7abe99bec5fe85e8b54a1d1c1.
