### ISSUE TITLE
Add total_supply for asset in API

### ISSUE THREAD

**Issue by allenpiscitello** [Blockstream/esplora#184]
While it can be calculated, it would be more convenient if the total supply of a token were available in the api.

This could be done by either making a new endpoint:

/api/asset/<hash>/total_supply

Or modifying 
api/asset/<hash>
to include it.

**Comment by rbensberg** [comment]
ACK - `Total Supply` or `Net Supply` perhaps. This is also useful for auditors of stablecoins for example to be able to quickly assess the veracity of the reported data.

**Comment by shesek** [comment]
So basically expose `issued_amount - burned_amount` as a separate field?

API wise, I would prefer to avoid adding redundant fields that can already be determined based on the other existing ones. But I can see merit in adding this to the esplora UI.

@greenaddress thoughts?

**Comment by shesek** [comment]
The circulating amount was added to the UI, both for issued assets and for the network's native asset. It is not exposed in the API though.

What it shows is basically this: `chain_stats.issued_amount + mempool_stats.issued_amount - chain_stats.burned_amount - mempool_stats.burned_amount`.

**Comment by shesek** [comment]
This was added in https://github.com/Blockstream/electrs/commit/b70e13de4f81bee225c411f3ddaab7df6c224a45 and documented [here](https://github.com/Blockstream/esplora/blob/master/API.md#get-assetasset_idsupply) (but still not deployed on the live servers). Also see #230.
