### ISSUE TITLE
Feature request: highlight relevant inputs and outputs for an address

### ISSUE THREAD

**Issue by fiatjaf** [Blockstream/esplora#188]
Suppose I'm looking for an output received on address `3En21bk76oS3j26GHHjRRswSbZD43jXTzW`.
I'll see this:

![2020-03-22-201234_944x747_scrot](https://user-images.githubusercontent.com/1653275/77264337-e4e04600-6c78-11ea-92e1-45513cddaefa.png)

It would be nice if the output `#6` was highlighted somehow there, like having a slightly different color or background color.

The same applies to transaction inputs. For example, if I'm looking in the page of address `bc1q3c6wwzsn2zqxs3nmank0jmpvske99g2duqjgjv` I see this:

![2020-03-22-204753_1021x413_scrot](https://user-images.githubusercontent.com/1653275/77266287-d21c4000-6c7d-11ea-904c-21078a5f4c7e.png)

The input `#1` could be highlighted there. I realize the API doesn't identify which inputs originate from one address for `/address/:address/txs`, but this could be achieved by matching each `vin` item in each outgoing transaction to a previous incoming transaction in the same address. Does this make sense?

**Comment by shesek** [comment]
This would indeed be very helpful. Another related feature request is #163. Will look into this!

**Comment by shesek** [comment]
Implemented in https://github.com/Blockstream/esplora/commit/4214b78cf98a85d482e88cc1552ebf57fb0c4b03, will go live with the next deployment.
