### ISSUE TITLE
search for liquid is higher than bitcoin mainnet and testnet

### ISSUE THREAD

**Issue by greenaddress** [Blockstream/esplora#193]
search for liquid is higher than bitcoin mainnet and testnet

expected: should be in the same spot

**Comment by shesek** [comment]
It looks like this was done intentionally by the designer, the liquid-mainnet `extras.css` file has some explicit CSS rules to position it differently from the other networks. I'm not sure why this was done, everything seems to look fine without this. I removed this in https://github.com/Blockstream/esplora/commit/01453497f36ad54b6a8e2b5eb988045626719b87, they should all look the same now.
