### ISSUE TITLE
Wrong fee on coinbase transaction

### ISSUE THREAD

**Issue by oliverlj** [Blockstream/esplora#198]
Transaction 6786501391b2d7de4fe38648ea6b76539a14707aaff959d7214a151fe4748e0e as example show a transaction fee of 184 467 440 724.5431 BTC

**Comment by darosior** [comment]
FWIW it doesn't appear on https://explorer.bitcoin-lyon.fr, I'm running on `7aefb8a0924cc78b01309c58945ea5db250db9c1`.

**Comment by shesek** [comment]
Nice catch, thanks!

Looks like a regression that was recently introduced due to some refactoring, resolved by https://github.com/Blockstream/electrs/commit/ef81d98a685cb721e78ab60c6a4e12fdd6d6d774.
