### ISSUE TITLE
Where is the blockchain processed?

### ISSUE THREAD

**Issue by educob** [Blockstream/esplora#20]
Hi.
I cannot find the file(s) that process the blockchain and save it to the database.

Could you please tell me where the processing is done?

Thanks.

**Comment by romanz** [comment]
Hello Eduardo,
The indexer code can be found here: https://github.com/Blockstream/electrs.
It uses REST API for queries (as documented [here](https://github.com/blockstream/esplora/blob/master/API.md)).

**Comment by greenaddress** [comment]
@educob more precisely the part of esplora that clones electrs can be found here https://github.com/Blockstream/esplora/blob/68c5fe930c6e24f271b0b6835bb8cafed0c5803b/Dockerfile.deps#L33

thanks @romanz !

**Comment by greenaddress** [comment]
closing
