### ISSUE TITLE
Tor version 0.3.4.9 not available

### ISSUE THREAD

**Issue by Kexkey** [Blockstream/esplora#200]
Hi,

Version 0.3.4.9 of Tor is not available anymore on the torproject dist repo.  I changed the version number to 0.4.2.7 in the following block in `Dockerfile.tor` and it fixed it:

```
ARG TOR_VER=0.3.4.9
ARG TORGZ=https://dist.torproject.org/tor-$TOR_VER.tar.gz
```

**Comment by greenaddress** [comment]
thanks @Kexkey - will fix!

**Comment by nitramiz** [comment]
Updated. https://github.com/Blockstream/esplora/commit/7b72fae11c9920d1165a976e21cc2e635d0fea37
