### ISSUE TITLE
Missing vsize attribute in the API

### ISSUE THREAD

**Issue by peername** [Blockstream/esplora#203]
For example:

https://blockstream.info/api/tx/653302087d7b1dfe2bcc936de6d719b09775f823680a00e6ac2e0661298eae43

There is only "size" attribute. "vsize" is more important and useful after SegWit.

**Comment by shesek** [comment]
The `vsize` is the `weight` divided by 4, which is available in the API.

**Comment by peername** [comment]
Thanks!
