### ISSUE TITLE
i.tryUnconfidentialAddress is not a function

### ISSUE THREAD

**Issue by cryptofuture** [Blockstream/esplora#204]
I get `i.tryUnconfidentialAddress is not a function` When trying to search for address and interface stuck at loading. However api request works fine.

**Comment by cryptofuture** [comment]
9990a22f13c12c2b2f642d1e4c64216d7086b724 should fix it, right?

**Comment by shesek** [comment]
Yes, 9990a22f13c12c2b2f642d1e4c64216d7086b724 fixes it and was deployed on the live server. Thanks for the report!
