### ISSUE TITLE
electrs: thread 'blkfiles_reader' panicked at 'failed to read "/bitcoin/blocks/blk01282.dat"'

### ISSUE THREAD

**Issue by Tomasvrba** [Blockstream/esplora#213]
Hi, I have been trying to build a tx index with Blockstream/electrs for the past week and I keep getting thread panics reliably at the same `.blk` file. This is the log with `RUST_BACKTRACE=full`:
```shell
TRACE - skipping block 000000000000000000241d2ab1d96f508562a039358dc05688b113e57a0d11a6
TRACE - fetched 0 blocks
DEBUG - writing 0 rows to RocksDB { path: "./lightmode-db/mainnet/newindex/history" }, flush=Disable
TRACE - reading "/bitcoin/blocks/blk01274.dat"
TRACE - parsing 133899572 bytes
TRACE - fetched 194 blocks
TRACE - reading "/bitcoin/blocks/blk01275.dat"
TRACE - parsing 133999670 bytes
TRACE - fetched 193 blocks
TRACE - reading "/bitcoin/blocks/blk01276.dat"
TRACE - parsing 133499147 bytes
TRACE - fetched 213 blocks
TRACE - reading "/bitcoin/blocks/blk01277.dat"
TRACE - parsing 133604705 bytes
TRACE - reading "/bitcoin/blocks/blk01278.dat"
TRACE - parsing 134162457 bytes
WARN - failed to export stats: failed to read stats
TRACE - reading "/bitcoin/blocks/blk01279.dat"
DEBUG - writing 1892451 rows to RocksDB { path: "./lightmode-db/mainnet/newindex/history" }, flush=Disable
TRACE - parsing 133347786 bytes
TRACE - reading "/bitcoin/blocks/blk01280.dat"
TRACE - fetched 138 blocks
DEBUG - writing 1927998 rows to RocksDB { path: "./lightmode-db/mainnet/newindex/history" }, flush=Disable
TRACE - parsing 133059996 bytes
TRACE - reading "/bitcoin/blocks/blk01281.dat"
TRACE - fetched 148 blocks
DEBUG - writing 1824775 rows to RocksDB { path: "./lightmode-db/mainnet/newindex/history" }, flush=Disable
TRACE - parsing 133214276 bytes
TRACE - reading "/bitcoin/blocks/blk01282.dat"
thread 'blkfiles_reader' panicked at 'failed to read "/bitcoin/blocks/blk01282.dat"', src/new_index/fetch.rs:161:63
stack backtrace:
TRACE - fetched 146 blocks
   0:     0x55dcfb428bc9 - <unknown>
   1:     0x55dcfb1d38ac - <unknown>
   2:     0x55dcfb428144 - <unknown>
   3:     0x55dcfb427d3b - <unknown>
   4:     0x55dcfb42743e - <unknown>
   5:     0x55dcfb42701a - <unknown>
   6:     0x55dcfb426fc0 - <unknown>
   7:     0x55dcfb2abc67 - <unknown>
   8:     0x55dcfb2abafa - <unknown>
   9:     0x55dcfb2aafed - <unknown>
  10:     0x55dcfb436e6e - <unknown>
  11:     0x55dcfb4383e6 - <unknown>
  12:     0x7f42eae04609 - <unknown>
  13:     0x7f42ead0e103 - clone
  14:                0x0 - <unknown>
Aborted (core dumped)
```

**cargo version**:  
```
cargo 1.43.0 (2cbe9048e 2020-05-03)
```  

**Bitcoin Core version**:  
```
Bitcoin Core version v0.19.1
```

* The panic at `blk01282.dat` happens reliably when building the `mainnet/newindex/history` index with `--lightmode`, but that is further than I get when running without lightmode.  
* Without `--lightmode` I get the same panic on the previous step when building `mainnet/newindex/txstore`, always at `blk01836.dat`

This is on a relatively powerful VPS, I even tried bumping up the specs to see if it would help, but even with 6 core CPU, 24 GB RAM and 1.5 TB SSD, this keeps happening. 

By the way, I tried `romanz/electrs` just to check, and it works completely fine, but I would like to use the esplora version for the REST API. This is a really amazing project.

Could this be because of Bitcoin Core 0.19.1? If it is some corruption in the `.blk` files, is there a way to tell Bitcoin Core to resync/reindex from/just a particular block so I don't have to reindex the whole chain? I haven't found out how.

This is the relevant `bitcoin.conf` part I am using:
```
server=1
prune=0
txindex=0
datadir=/bitcoin
```

Any help would be much appreciated.

**Comment by shesek** [comment]
It seems like its failing to read file, before even trying to parse it. Seems pretty odd.

I made it display a more useful error message in https://github.com/Blockstream/electrs/commit/6c532341389ebb82b0ba4e147d77f7652dab3d3b. Could you try again with this and see what error message you get?

**Comment by Tomasvrba** [comment]
> It seems like its failing to read the file, before even trying to parse it. Pretty odd.
> 
> I made it display a more useful error message in [Blockstream/electrs@6c53234](https://github.com/Blockstream/electrs/commit/6c532341389ebb82b0ba4e147d77f7652dab3d3b). Could you try again with this and see what error message you get?

Thanks for the quick response.

Here's the error message: `"Too many open files"`
```
thread 'blkfiles_reader' panicked at 'failed to read "/bitcoin/blocks/blk01282.dat": Os { code: 24, kind: Other, message: "Too many open files" }', src/new_index/fetch.rs:162:41
```

This is running on Ubuntu 20.04 and `ext4` filesystem.

I am looking into where this coming from, whether this is specific to the Rust reader, bu I am not very familiar with Rust

**Comment by Tomasvrba** [comment]
This was because of an open file limit on the OS. The limit for the `bitcoin` user was
```shell
$ ulimit -Sn
1024
```
Increasing the limit solved the issue and the index is continuing to build now.
