### ISSUE TITLE
Error 500 for style.css and error 404 for /api/ calls

### ISSUE THREAD

**Issue by tecnique2** [Blockstream/esplora#216]
Hi all,

I have just installed esplora on Ubuntu 18.04 (following exactly the description).

```
git clone https://github.com/Blockstream/esplora && cd esplora
npm install
export API_URL=http://localhost:3000/
npm run dev-server
```

The API_URL points to blockstream.info, because electr is still indexing (and will be for some days).

`export API_URL=https://blockstream.info/api/`

If I start the server with: `npm run dev-server` everything runs without errors and messages: `HTTP server running on :::5000` at the end.

If I point my browser to localhost:5000 the /style.css file is not loaded and the terminal shows the following error for it:
```
GET /style.css 500 29.048 ms - 1108
TypeError: Cannot read property 'readFile' of undefined
    at map (/home/xxx/esplora/dev-server.js:44:80)
    at Array.map (<anonymous>)
    at _callee2$ (/home/xxx/esplora/dev-server.js:44:64)
    at tryCatch (/home/xxx/esplora/node_modules/@babel/node/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/xxx/esplora/node_modules/@babel/node/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/home/xxx/esplora/node_modules/@babel/node/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/xxx/esplora/dev-server.js:37:103)
    at _next (/home/xxx/esplora/dev-server.js:39:194)
    at /home/xxx/esplora/dev-server.js:39:364
    at new Promise (<anonymous>)
```

And if I point my browser to the /api (f.e. http://localhost/5000/api/address/XXXX) I only get a 404 message.

I have googled all this for a while and tried some reinstalls.
But I can't figure out, what is wrong here.
So I would be thankful for some help!

**Comment by tecnique2** [comment]
Solved the style.css problem.
After upgrading node.js from v8.10.0 (stable) to v14.4.0 (latest) the style.css file works fine (status 200).
Now I only have to find a solution for the /api 404 error.

**Comment by shesek** [comment]
The web server at `http://localhost:5000/` serves the client-side UI only, API requests should go directly to `http://localhost:3000/` and not via `http://localhost:5000/api/`.

The setup on blockstream.info is a bit different, its deployed with docker and uses a frontend nginx server that forwards requests from `/api/` to the API server and other requests to the UI server. If you're not using the docker/nginx setup, you won't have this.

**Comment by shesek** [comment]
Note that when the UI and API are served from different origins, you will need to set `--cors` on the electrs side to allow cross-origin requests.

**Comment by tecnique2** [comment]
Ok, so now it makes sense.
I just have to wait until electrs finished with indexing and then I can call the API on http://localhost:3000 
Thank you very much!
