### ISSUE TITLE
Electrs crashes with electrum node discovery returning localhost

### ISSUE THREAD

**Issue by shyrwall** [Blockstream/esplora#218]
Hi

Unable to submit issues for Electrs directly.

If running with electrum node discovery and a discovered node's ip is 127.0.0.1 electrs crashes. I assume because trying to connect to itself?

DEBUG - tardis.bauerj.eu Ssl(50002) is available
thread 'discovery-jobs' panicked at 'assertion failed: healthy.entry(addr).or_insert_with(||
                                       Server::new(job.hostname.clone(),
                                                   features)).services.insert(job.service)', src/electrum/discovery.rs:295:9

host tardis.bauerj.eu
tardis.bauerj.eu is an alias for schiaparelli.bauerj.eu.
schiaparelli.bauerj.eu has address 127.0.0.1

**Comment by shesek** [comment]
What commit are you running from? An explicit test that rejects local IP addresses was added about 10 days ago, in https://github.com/Blockstream/electrs/commit/4674d981182d88ad58c0fd87a539d8d9d037c86c.

But regardless, the error that you're seeing doesn't seem related to it being 127.0.0.1. It looks like a database inconsistency, its expecting to save a new healthy service that shouldn't previously exists in the list of healthy services, but somehow it already does.

Could you send me some more of the log, to see what happened earlier? (make sure to scrub anything that seems sensitive, and you can also send it privately to me if you prefer. I'm available at nadav@shesek.info or @shesek on twitter).

**Comment by shyrwall** [comment]
Hi. I ran one with that commit. Now running the latest commit and same error. See attached file.
[err-218.txt](https://github.com/Blockstream/esplora/files/4866434/err-218.txt)

**Comment by shesek** [comment]
This was fixed by https://github.com/Blockstream/electrs/commit/edc7d8b0703b15196ad5c5315d4f8a87ada40ea7, which removed the assert.
