### ISSUE TITLE
Size of txstore

### ISSUE THREAD

**Issue by Naryck** [Blockstream/esplora#219]
Is there a way of reducing size of Electrs data of BTC blockchain? Or this is normal size for the current blockchain state?
What I see now in electrs:
```
/mnt/bitcoin/electrs/db/mainnet/newindex$ du -sh */
16M     cache/
213G    history/
409G    txstore/
```
All this space is occupied by **.sst** files:
```
/mnt/bitcoin/electrs/db/mainnet/newindex/txstore$ du -ch *.sst | grep total
409G    total
```

**Comment by shesek** [comment]
You can cut storage requirements by roughly 50% by enabling lightmode, see [more details here](https://github.com/Blockstream/electrs/#light-mode).
