### ISSUE TITLE
README port indication

### ISSUE THREAD

**Issue by AntoineXBTO** [Blockstream/esplora#22]
Hi,

It seems like the actual default port (on which the front end is running) is 5000 instead of 3000.
https://github.com/Blockstream/esplora#configuration-options

For the API_URL (https://github.com/Blockstream/esplora#developing), it should be pointing to http://localhost:3000/, which is where electrs is listening by default.

Is that correct?

**Comment by greenaddress** [comment]
Hi @AntoineXBTO - you are correct, the example is wrong, should have been 3000 not 5000. I will fix it.
