### ISSUE TITLE
mistake of statistics funded_txo_count and spent_txo_count tx_count

### ISSUE THREAD

**Issue by chenluyong** [Blockstream/esplora#221]
The `input` and `output` are not equal to the `tx_count`

For example: https://blockstream.info/address/1LZfNmse6v22xKtqUtKmVuFqZMVhxVJbyN

There are many similar cases.

```
1LLQFPBXB9HwjHPnqKYmaBaw7GBx4odch2
1NDyJtNTjmwk5xPNhjgAMu4HDHigtobu1s
```

**Comment by shesek** [comment]
`funded_txo_count` and `spent_txo_count` counts outputs that fund the given address and inputs that spend from the given address, which could differ from the number of transactions if there are multiple outputs/inputs affecting the address within a single transaction.

**Comment by chenluyong** [comment]
This means if `input` and `output` both have `1LLQFPBXB9HwjHPnqKYmaBaw7GBx4odch2` in the transaction, then `spent_txo_count` increases by 1 and `funded_txo_count` by 1

**Comment by chenluyong** [comment]
`tx_count` != `funded_txo_count ` + `spent_txo_count`

Is this what `Blockstream` wants?

**Comment by shesek** [comment]
> `tx_count` != `funded_txo_count ` + `spent_txo_count`

Indeed. They're counting different things. Note that this doesn't say `funded_tx_count` and `spent_tx_count`, but specifically refers to `txo`s...
