### ISSUE TITLE
[Docker] electrs over unix socket does not work

### ISSUE THREAD

**Issue by zpv** [Blockstream/esplora#229]
A recent change was made to use electrs over unix sockets instead of TCP.
https://github.com/Blockstream/esplora/blob/65bf3f72ef367ba016588491c312b4f80c0b9c56/contrib/nginx.conf.in#L16

However, for some reason, it fails to work when following the instructions for Docker, returning a 502 Bad Gateway after being synced. Perhaps an outdated electrs version? (doesn't seem to be the case)

Manually changing electrs and nginx to use TCP fixes the problem.

**Comment by shesek** [comment]
Thanks for the report! This was fixed by https://github.com/Blockstream/esplora/commit/db0c22607a304f897f5f7a2707d8b0a8466ce5c0.

**Comment by demian85** [comment]
I bumped into this issue and I don't know how to solve it. Can someone please help?
```2021/03/18 13:57:25 [crit] 153#153: *59 connect() to unix:/var/electrs-rest.sock failed (2: No such file or directory) while connecting to upstream, client: 46.53.242.215, server: , request: "GET /api/blocks/ HTTP/1.1", upstream: "http://unix:/var/electrs-rest.sock:/blocks/", host: "54.242.81.76:8080"``` 

I don't know what's going on.

**Comment by shesek** [comment]
@demian85 Is this with the docker setup?

**Comment by demian85** [comment]
Yes

**Comment by demian85** [comment]
Cannot even run electr:
```
root@7e32f5f6fecf:/var# RUST_BACKTRACE=full /srv/explorer/electrs_bitcoin/bin/electrs --timestamp --http-addr 127.0.0.1:3000 --network mainnet --daemon-dir /data/bitcoin --monitoring-addr 0.0.0.0:4224 --electrum-rpc-addr 0.0.0.0:50001 --electrum-txs-limit 100000 --db-dir /data/electrs_bitcoin_db/mainnet --tor-proxy 127.0.0.1:9050  -vvvv --address-search
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: Bitcoin, db_path: "/data/electrs_bitcoin_db/mainnet/mainnet", daemon_dir: "/data/bitcoin", blocks_dir: "/data/bitcoin/blocks", daemon_rpc_addr: 127.0.0.1:8332, cookie: None, electrum_rpc_addr: 0.0.0.0:50001, http_addr: 127.0.0.1:3000, http_socket_file: None, monitoring_addr: 0.0.0.0:4224, jsonrpc_import: false, light_mode: false, address_search: true, index_unspendables: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 100000, electrum_banner: "Welcome to electrs-esplora 0.4.1", electrum_public_hosts: None, electrum_announce: false, tor_proxy: Some(127.0.0.1:9050) }
thread 'main' panicked at 'failed to start monitoring HTTP server at 0.0.0.0:4224', src/metrics.rs:71:33
stack backtrace:
   0:     0x561008552bea - <unknown>
   1:     0x5610081fcc1c - <unknown>
   2:     0x561008552361 - <unknown>
   3:     0x561008551da0 - <unknown>
   4:     0x561008551653 - <unknown>
   5:     0x56100856ff8d - <unknown>
   6:     0x56100856fefc - <unknown>
   7:     0x56100856fead - <unknown>
   8:     0x56100856fe20 - <unknown>
   9:     0x5610082bface - <unknown>
  10:     0x561008176266 - <unknown>
  11:     0x5610081655e3 - <unknown>
  12:     0x561008177848 - <unknown>
  13:     0x7f090230b09b - __libc_start_main
  14:     0x5610081652ba - <unknown>
  15:                0x0 - <unknown>
Aborted (core dumped)```

**Comment by shesek** [comment]
It appears that you're trying to manually run electrs inside the container, is it possible that electrs is already running as a background daemon on that container too?

The error message seems to indicate that, the `4224` port cannot be bound because its already used.

If you want to test that electrs starts up properly, you can try running it with different ports so it doesn't conflict. Or just look through the logs of existing electrs background instance instead.
