### ISSUE TITLE
QR code for liquid address prefixes bitcoin: and scan from Green mobile fails

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/esplora#232]
e.g. on this page:

https://blockstream.info/liquid/address/VTq2xrGoMBoJwM83uWEQLsduu4Y1pembfDWSJMyFEsHgYBmrcHRXZJqVL67GAfBtv92Po4Mnmcn16PWW

The QR code scans as `bitcoin:VTq2xrGoMBoJwM83uWEQLsduu4Y1pembfDWSJMyFEsHgYBmrcHRXZJqVL67GAfBtv92Po4Mnmcn16PWW`

Which Green mobile says is invalid. Green desktop etc generates QR codes with no prefix, just the address and that scans from mobile just fine.

I was scanning to send L-BTC from a Liquid Securities sub account but don't think it should matter.

**Comment by shesek** [comment]
Thanks for reporting this! Fixed in https://github.com/Blockstream/esplora/commit/6f252e5d817cb48174c8b39b244ac4f60382936d.
