### ISSUE TITLE
Verbose transactions are currently unsupported - on 'electrs-esplora' 

### ISSUE THREAD

**Issue by leonardojobim** [Blockstream/esplora#235]
When connected to  [ 'electrs-esplora 0.4.1', '1.4' ], the RPC command 'blockchain.transaction.get' with verbose = true returns the error message: verbose transactions are currently unsupported - on 'electrs-esplora 0.4.1', '1.4'  .

**Comment by Axe-gift** [comment]
H

**Comment by Axe-gift** [comment]
Iam

**Comment by nkuba** [comment]
See https://github.com/Blockstream/electrs/pull/36

**Comment by shesek** [comment]
Closing as a duplicate of https://github.com/Blockstream/electrs/pull/36.
