### ISSUE TITLE
Search does not work for blech32 addresses for Liquid

### ISSUE THREAD

**Issue by allenpiscitello** [Blockstream/esplora#236]
Search for lq1qqf6stv8pql23rgjyylmv7e5np5yrl8hk7zv7ll5dq89gfst8kh9exs5k5e7vdqahlrsqvu88uhsdgwvy7en0ks4ds03r737jk on Liquid. Nothing found.

Go to:

https://blockstream.info/liquid/address/lq1qqf6stv8pql23rgjyylmv7e5np5yrl8hk7zv7ll5dq89gfst8kh9exs5k5e7vdqahlrsqvu88uhsdgwvy7en0ks4ds03r737jk

This works.

**Comment by shesek** [comment]
Fixed by https://github.com/Blockstream/esplora/commit/fdf7d5f8f41c2e787f25de6117c39e268b5fdc41.
