### ISSUE TITLE
feature to get merkle proofs for confirmed transactions

### ISSUE THREAD

**Issue by instagibbs** [Blockstream/esplora#24]
Would be nice for elements/liquid.

**Comment by shesek** [comment]
There actually already is an endpoint that provides merkle inclusion proofs: https://github.com/blockstream/esplora/blob/master/API.md#get-txtxidmerkle-proof

But it provides the proofs in Electrum's format, which probably isn't what you need. Changing to the `merkleblock` format is a TODO.

**Comment by shesek** [comment]
Implemented in https://github.com/Blockstream/electrs/commit/cfe94306e22450d347374205637082b25b2cd0c2, available as [`GET /tx/:txid/merkleblock-proof`](https://github.com/blockstream/esplora/blob/master/API.md#get-txtxidmerkleblock-proof).

**Comment by shesek** [comment]
Note that this is currently not implemented for elements-based chains, because rust-bitcoin's `MerkleBlock` expects to work with its own `BlockHeader` struct and won't accept rust-elements's `BlockHeader`.
