### ISSUE TITLE
Thread 'main' panicked after full compaction

### ISSUE THREAD

**Issue by Bitorzo** [Blockstream/esplora#248]
DEBUG - starting full compaction on RocksDB { path: "/X/electrs/db/mainnet/newindex/txstore" }
WARN - failed to export stats: failed to read stats
WARN - failed to export stats: failed to read stats
WARN - failed to export stats: failed to read stats
WARN - failed to export stats: failed to read stats
WARN - failed to export stats: failed to read stats
DEBUG - finished full compaction on RocksDB { path: "/X/db/mainnet/newindex/txstore" }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: While open a file for random read: /X/db/mainnet/newindex/txstore/000592.sst: Too many open files" }', src/new_index/db.rs:192:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by Bitorzo** [comment]
Solved by changing the open files limits.

**Comment by demian85** [comment]
and how did you do that while running on Docker?
