### ISSUE TITLE
Please add date to transactions

### ISSUE THREAD

**Issue by darbsllim** [Blockstream/esplora#25]
Currently there is no date field when viewing a transaction, please add that so it's easy to see when the transaction was sent.

**Comment by greenaddress** [comment]
We had https://github.com/Blockstream/esplora/issues/10 raised to add the timestamp from the block (so only for confirmed transactions) .

Is that sufficient or you meant when the transaction was first seen (so inclusive of mempool)? 

First seen would be inconsistent between different nodes so we would be showing [slightly] different values depending on what instance you hit if we were to do it at first seen (we have multiple instances behind a load balancer for example)

**Comment by greenaddress** [comment]
@darbsllim ping :)

**Comment by Liongrass** [comment]
Very much second this feature request! At the very least it should be easy to see what day/time a transaction was confirmed. If there was data on when the transaction was first seen it would be even more useful

**Comment by greenaddress** [comment]
this has been added. thanks! closing
