### ISSUE TITLE
Docker Esplora Image: environment variable ENABLE_LIGHTMODE=1 not honored

### ISSUE THREAD

**Issue by clintmasden** [Blockstream/esplora#250]
Docker:
docker run --name esplora-container-light -e ENABLE_LIGHTMODE=1 -e NO_PRECACHE=1 -e NO_ADDRESS_SEARCH=1  -p 50001:50001 -p 8080:80 --volume F:\blockstream-esplora-light:/data -i -t blockstream/esplora:fdf7d5f8f41c2e787f25de6117c39e268b5fdc41 bash -c "/srv/explorer/run.sh bitcoin-mainnet explorer"

Config output:
2-Config { log: StdErrLog { verbosity: Info, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Never }, network_type: Bitcoin, db_path: "/data/electrs_bitcoin_db/mainnet/mainnet", daemon_dir: "/data/bitcoin", blocks_dir: "/data/bitcoin/blocks", daemon_rpc_addr: V4(127.0.0.1:8332), cookie: None, electrum_rpc_addr: V4(0.0.0.0:50001), http_addr: V4(127.0.0.1:3000), http_socket_file: Some("/var/electrs-rest.sock"), monitoring_addr: V4(0.0.0.0:4224), jsonrpc_import: false, light_mode: false, address_search: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 100000, electrum_banner: "Welcome to electrs-esplora 0.4.1", electrum_public_hosts: None, electrum_announce: false, tor_proxy: Some(V4(127.0.0.1:9050)) }

This is with the latest image/pull from docker hub.

---

Found the issue which spawned from this commit
https://github.com/Blockstream/esplora/commit/6f96e9c2263ab31c080a92200339606a27949f2d

In run.sh you still have the following:

if [ -n "$ENABLE_REDUCED_STORAGE" ]; then
    ELECTRS_ARGS="$ELECTRS_ARGS --reduced-storage"
fi

Replace with:

if [ -n "$ENABLE_LIGHTMODE" ]; then
    ELECTRS_ARGS="$ELECTRS_ARGS --lightmode"
fi

I'm using a local image for now yet it's an easy fix to recommit/deploy

Config after replacing reduced_storage and adding in enable_lightmode:
2-Config { log: StdErrLog { verbosity: Info, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Never }, network_type: Bitcoin, db_path: "/data/electrs_bitcoin_db/mainnet/mainnet", daemon_dir: "/data/bitcoin", blocks_dir: "/data/bitcoin/blocks", daemon_rpc_addr: V4(127.0.0.1:8332), cookie: None, electrum_rpc_addr: V4(0.0.0.0:50001), http_addr: V4(127.0.0.1:3000), http_socket_file: Some("/var/electrs-rest.sock"), monitoring_addr: V4(0.0.0.0:4224), jsonrpc_import: false, light_mode: true, address_search: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 100000, electrum_banner: "Welcome to electrs-esplora 0.4.1", electrum_public_hosts: None, electrum_announce: false, tor_proxy: Some(V4(127.0.0.1:9050)) }

**Comment by shesek** [comment]
Good catch, thanks for reporting this! Not sure how this slipped through :)

Fixed in https://github.com/Blockstream/esplora/commit/047fe9d38f46506ee2fc7435428d213f1ebd3f4d.

**Comment by clintmasden** [comment]
You are welcome, keep up the great work.
