### ISSUE TITLE
Stuck on full compaction - 1 hr

### ISSUE THREAD

**Issue by baebb** [Blockstream/esplora#251]
```2020-08-31T05:33:22.659+00:00 - DEBUG - starting full compaction on RocksDB { path: "/mnt/volume_sgp1_01/mainnet/newindex/txstore" }```

Had this happen before so I killed it, removed db files and started fresh. How long should I wait?

Server specs: 8GB memory, 2TB volume, Ubuntu 18.04.3 

Updated: Self-Killed after 2hrs. No reason specified

**Comment by shesek** [comment]
What is your open file limit? Can you try increasing it with `ulimit -n`?

Are you using an SSD?

Strange that it self-killed without issuing some sort of an error message. Was "starting full compaction on RocksDB" the last log message shown?

**Comment by baebb** [comment]
@shesek thanks for the reply

- I had bumped open file limit to 65535 already
- Storage is SSD
- `starting full compaction on RocksDB` is the last message, yes

**Comment by shesek** [comment]
Can you check your system log for relevant messages around the time the electrs daemon stopped?

**Comment by baebb** [comment]
@shesek which log file should I be looking into?
<img width="543" alt="image" src="https://user-images.githubusercontent.com/8374514/92318862-3032b900-f04d-11ea-9a64-da86c4524bb4.png">

**Comment by Ariefiswahyudi** [comment]
Y

**Comment by shesek** [comment]
Try looking in `/var/log/syslog` (though by now it might've already been rotated into one of the numbered `syslog.N` files)

**Comment by baebb** [comment]
@shesek in the last few attempts I've gotten `std::bad_alloc` error when trying to start up electrs [instead of being stuck on full compaction] . I think this is a memory issue so I will bump node memory and see if that fixes things. I will update here

**Comment by baebb** [comment]
@shesek upgraded to a new droplet with 16GB ram, 8 vCPUs, Ubuntu 20.04 but still getting the same suck on full compaction issue 

Here is the syslog when things go wrong:

```
Sep 10 08:53:01 btc-mainnet kernel: [12567.732958] INFO: task electrs:21439 blocked for more than 120 seconds.
Sep 10 08:53:01 btc-mainnet kernel: [12567.734661]       Not tainted 5.4.0-47-generic #51-Ubuntu
Sep 10 08:53:01 btc-mainnet kernel: [12567.736082] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 10 08:53:01 btc-mainnet kernel: [12567.738065] electrs         D    0 21439  21365 0x00000000
Sep 10 08:53:01 btc-mainnet kernel: [12567.738068] Call Trace:
Sep 10 08:53:01 btc-mainnet kernel: [12567.738076]  __schedule+0x2e3/0x740
Sep 10 08:53:01 btc-mainnet kernel: [12567.738079]  ? __wake_up_common_lock+0x8a/0xc0
Sep 10 08:53:01 btc-mainnet kernel: [12567.738081]  schedule+0x42/0xb0
Sep 10 08:53:01 btc-mainnet kernel: [12567.738084]  jbd2_log_wait_commit+0xaf/0x120
Sep 10 08:53:01 btc-mainnet kernel: [12567.738085]  ? wait_woken+0x80/0x80
Sep 10 08:53:01 btc-mainnet kernel: [12567.738088]  __jbd2_journal_force_commit+0x61/0xb0
Sep 10 08:53:01 btc-mainnet kernel: [12567.738094]  jbd2_journal_force_commit+0x21/0x30
Sep 10 08:53:01 btc-mainnet kernel: [12567.738096]  ext4_force_commit+0x2a/0x2c
Sep 10 08:53:01 btc-mainnet kernel: [12567.738098]  ext4_sync_file+0x154/0x3b0
Sep 10 08:53:01 btc-mainnet kernel: [12567.738101]  vfs_fsync_range+0x49/0x80
Sep 10 08:53:01 btc-mainnet kernel: [12567.738105]  ? __fget_light+0x57/0x70
Sep 10 08:53:01 btc-mainnet kernel: [12567.738108]  do_fsync+0x3d/0x70
Sep 10 08:53:01 btc-mainnet kernel: [12567.738111]  __x64_sys_fsync+0x14/0x20
Sep 10 08:53:01 btc-mainnet kernel: [12567.738118]  do_syscall_64+0x57/0x190
Sep 10 08:53:01 btc-mainnet kernel: [12567.738121]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Sep 10 08:53:01 btc-mainnet kernel: [12567.738124] RIP: 0033:0x7f7ccd3578db
Sep 10 08:53:01 btc-mainnet kernel: [12567.738130] Code: Bad RIP value.
Sep 10 08:53:01 btc-mainnet kernel: [12567.738137] RSP: 002b:00007ffe78c63990 EFLAGS: 00000293 ORIG_RAX: 000000000000004a
Sep 10 08:53:01 btc-mainnet kernel: [12567.738144] RAX: ffffffffffffffda RBX: 00007ffe78c63ab0 RCX: 00007f7ccd3578db
Sep 10 08:53:01 btc-mainnet kernel: [12567.738145] RDX: 00007ffe78c63a20 RSI: 000055ddf16266e0 RDI: 000000000000000a
Sep 10 08:53:01 btc-mainnet kernel: [12567.738149] RBP: 00007ffe78c63a50 R08: 0000000000000000 R09: 00007ffe78c63258
Sep 10 08:53:01 btc-mainnet kernel: [12567.738154] R10: 00007ffe78c63250 R11: 0000000000000293 R12: 00007ffe78c63a30
Sep 10 08:53:01 btc-mainnet kernel: [12567.738155] R13: 00007ffe78c63a60 R14: 00007ffe78c63ca0 R15: 00007ffe78c63c60
```

Any ideas for what we can try?

**Comment by Axe-gift** [comment]
Yup

**Comment by baebb** [comment]
Solved this. Just had to retry and wait a bunch of times 👍
