### ISSUE TITLE
How to specify non-standard bitcoind data dir

### ISSUE THREAD

**Issue by jodobear** [Blockstream/esplora#252]
I wasn't able to find in the documentation regarding non-std btc data dir. Can i run esplora docker container by adding `daemon-dir` like so:

```sh
sudo docker run -d -p 50001:50001 -p 8080:80 \
            --restart unless-stopped \
            --daemon-dir "$BTC_DATA_DIR"/.bitcoin \
            --volume "$ESPLORA_DATA_DIR" \
            -e ONION_URL=http://xyz.onion \
            -e ENABLE_LIGHTMODE=1 \
            -e NO_PRECACHE=1 \
            -t esplora \
            bash -c "/srv/explorer/run.sh $ESPLORA_NETWORK explorer"
```sh

Since, my server is still doing IBD, I'm not able to test it. Also, is this how i make the esplora service persistent? Since, the docker command in the docs removes the container once shut.

Thanks for the awesome work!

**Comment by shesek** [comment]
The docker image sets up its own bitcoind node. If you already have a running bitcoind node that you'd like to use instead, you'll have to setup esplora/electrs manually and not with docker.

You can find instructions for doing that here:  https://bitcoin.stackexchange.com/a/91859

I'm closing this, but please do report back if you're having any issues.
