### ISSUE TITLE
Incorrect Fee Rate Calculation

### ISSUE THREAD

**Issue by benthecarman** [Blockstream/esplora#255]
For transaction: https://blockstream.info/testnet/tx/d34888da65ece048d41e0c74a59f225bbe7326e5f8c7437a4bf4df487822b3d3

It notes that there is a fee paid of 24131 sats, and a vsize of 164 vB. For the fee rate it denotes 147.8 sats/vB, however, `24131/164 = 147.14`.

**Comment by shesek** [comment]
The calculation is done using weight units and converted to sat/vbyte, which gives a more accurate result compared to the using the rounded vbytes.

`24131 / 653 * 4 = 147.81623277182237`
