### ISSUE TITLE
Failed to connect daemon at 172.18.0.2:8332 When running Blockstream/Electrs from Docker

### ISSUE THREAD

**Issue by Trudko** [Blockstream/esplora#260]
I am trying to run esplora / electrs from inside of docker containers. I am using blockstream/bitcoind docker image with blockstream/electrs.

Steps to reproduce:

1. Create new docker network - sudo docker network create my-net
2. Pull bitcoind image - docker pull blockstream/bitcoind
3. Run the image- sudo docker run --name bitcoind --network=my-net  -it -d -e 'BTC_RPCUSER=bitcoin' -e 'BTC_TXINDEX=1' --env-file envfile -v /home/ubuntu/bitcoin_data:/root/.bitcoin/ -p 127.0.0.1:8334:8332 -p 8335:8333 blockstream/bitcoind
4. Attach into the image - docker start bitcoind exec bash
7. Create a bitcoin.conf with contents:
```
rpcallowip=0.0.0.0/0
rpcbind=127.0.0.1
rpcbind=bitcoind
rpcuser=bitcoin
rpcpassword=btc
maxuploadtarget=144
```
8. Create a cookie file mycookie with user:password contents 
9. Start / restart bitcoin node using bitcoind -daemon 
10. Build  and run electrs:
```
docker run -p 50001:50001 -p 8080:80 -p 3000:3000 --network=my-net --volume $HOME/bitcoin_data:/home/user/.bitcoin:ro --volume $PWD:/home/user/electrs_data --rm -i -t  -e ELECTRS_DAEMON_RPC_ADDR='bitcoind:8332' electrs electrs -vvvv --timestamp  --daemon-dir ~/.bitcoin --timestamp  --db-dir /home/user/electrs_data --cookie-file /home/user/.bitcoin/mycookie
```

output:
```
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "/home/user/electrs_data/mainnet", daemon_dir: "/home/ubuntu/.bitcoin", blocks_dir: "/home/ubuntu/.bitcoin/blocks", daemon_rpc_addr: V4(172.18.0.2:8332), electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 4, tx_cache_size: 10485760, txid_limit: 100, server_banner: "Welcome to electrs 0.8.5 (Electrum Rust Server)!", blocktxids_cache_size: 10485760 }
2020-10-06T11:09:44.454+00:00 - DEBUG - Server listening on 127.0.0.1:4224
2020-10-06T11:09:44.454+00:00 - DEBUG - Running accept thread
2020-10-06T11:09:44.455+00:00 - **WARN - failed to connect daemon at 172.18.0.2:8332**: Connection refused (os error 111)
```

I've tried to run dummy server from inside bitcoind docker on port 80 and that was accessible using curl from within electrs container. 

Bitcoind container is accessible through bitcoind host name from within electrs container as both container are on the same my-net network (double checked via docker network inspect my-net)

Bitcoind jsonrpc was accessible from docker host on port 8332. I could run curl --user bitcoin --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' -H 'content-type: text/plain;' 127.0.0.1:8332 and get output:

```
{"result":{"chain":"main","blocks":651511,"headers":651511,"bestblockhash":"0000000000000000000083402925438dc9fa5df2c642b63ec66142c1fc9a89d7","difficulty":19298087186262.61,"mediantime":1601978524,"verificationprogress":0.9999997643173912,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000001456bba7a04976ea8f2e1320","size_on_disk":344395134285,"pruned":false,"softforks":{"bip34":{"type":"buried","active":true,"height":227931},"bip66":{"type":"buried","active":true,"height":363725},"bip65":{"type":"buried","active":true,"height":388381},"csv":{"type":"buried","active":true,"height":419328},"segwit":{"type":"buried","active":true,"height":481824}},"warnings":""},"error":null,"id":"curltest"}
```

I've tried esplora too by running:
```
1. sudo docker pull blockstream/esplorasudo docker pull blockstream/esplora
2. sudo docker run -p 50001:50001 -p 8080:80 --volume $PWD/bitcoin_data:/data --rm -i -t blockstream/esplora bash -c "/srv/explorer/run.sh bitcoin-mainnet explorer"
```
it seem to be doing something but when shut it down I also get warnings:

2-2020-10-06T11:14:25.206+00:00 - WARN - reconnecting to bitcoind: failed to read cookie from "/data/bitcoin/.cookie"
2-2020-10-06T11:14:28.206+00:00 - WARN - failed to connect daemon at 127.0.0.1:8332: Connection refused (os error 111)

Those make sense because I didn't set proper path to cookie and didnt change(how can I?) daemon url which should bitcoind:8332 

My suspicion is bitcoin.conf setting and rpcallowedip, but I couldnt find proper setting. Thank you!

**Comment by Trudko** [comment]
Slight update now I am getting:

 WARN - reconnecting to bitcoind: disconnected from daemon while receiving , seems like it connects but fails afterwards.

**Comment by shesek** [comment]
What is `blockstream/bitcoind`? There's no such image on docker hub. You should be using `blockstream/esplora` which includes bitcoind+espora+electrs+nginx.

**Comment by shesek** [comment]
Ah, I just noticed that you're the same one that reported something similar in https://github.com/Blockstream/esplora/issues/45#issuecomment-704765796.  See my reply there.
