### ISSUE TITLE
ETA via API

### ISSUE THREAD

**Issue by wchance** [Blockstream/esplora#262]
![image](https://user-images.githubusercontent.com/7815792/95502899-8fe7f100-0978-11eb-9125-b35997e7c86a.png)

Is there a way to get ETA value show in web interface via API?

Not seeing it in 

http://10.2.0.16:8080/api/tx/{txid} or http://10.2.0.16:8080/api/tx/{hash}/status

would be nice to include in hash status

**Comment by shesek** [comment]
It is not available via the API. This information is calculated on the client-side, based on the transaction's fee rate, the fee estimates and the mempool fee histogram.

- "in *X* blocks" is determined by fetching the [fee estimates](https://github.com/Blockstream/esplora/blob/master/API.md#get-fee-estimates) and looking for highest estimate that's lower than what the transaction is paying. For example, if the estimates are 10 sat/vB for inclusion in 2 blocks, 5 sat/vB for 3 blocks and 1 sat/vB for 4 blocks, a transaction paying 7 sat/vB will have an ETA of 3 blocks. You can see the code implementing this [here](https://github.com/Blockstream/esplora/blob/52c77d879aaed6b43b191279519845cfc07638f9/client/src/lib/fees.js#L13-L19).

- "*X* vMB from tip" is determined by fetching the [mempool fee histogram](https://github.com/Blockstream/esplora/blob/master/API.md#get-mempool) and summing the total vsize of the entries with a higher fee rate compared to the transaction. You can see the code implementing this [here](https://github.com/Blockstream/esplora/blob/52c77d879aaed6b43b191279519845cfc07638f9/client/src/lib/fees.js#L6-L11).

Making this available via the API could potentially make sense. Can you tell me more about your use case?

**Comment by wchance** [comment]
thanks for explanation.   I think we may be able to do it as well client side and not need api modification.   I will close ticket once I implement in next 72 hours.

**Comment by wchance** [comment]
@shesek please let me know if you provide consulting services.

**Comment by shesek** [comment]
I'm afraid that my hands are too full to take on paid work. But could you tell me more about what you need? Maybe I can still help somehow.

**Comment by wchance** [comment]
I need to be able to approve transactions in the mempool before they are confirmed.   Was thinking that perhaps RBF field would be enough to insure that transaction can not be double spent.   Along with perhaps accessing the fee paid and the time it will take to be confirmed.

**Comment by shesek** [comment]
@wchance First, you should be aware that the only real guarantee against double-spending is on-chain confirmations. You can implement some heuristics that will make double-spending somewhat more difficult, but there'll always be some risk that needs to be managed. I think that this could sometimes be reasonable, depending on the specific case and the amounts involved.

But assuming that you're willing to deal with this risk, a couple things to note:

- Regarding RBF, you'll also want to check the the transaction doesn't have any unconfirmed ancestor transactions that opted-into RBF, which indirectly makes the child transaction RBF-able as well.

- Regarding fee rate, you should also take the fee rate of unconfirmed ancestor transactions into account. For example, if tx A is paying 1 sat/vB and tx B spends an output from A with 100 sat/vB, the effective fee rate paid by tx B is 50 sat/vB and not 100 sat/vB (assuming both A and B are unconfirmed and weight about the same).

Unfortunately, Esplora doesn't provide an easy way to do either of these two. A different project I'm working on called bwt, however, [does](https://github.com/shesek/bwt#wallet-transaction-format) (look for `effective_feerate` and `bip125_replacelable`). But its a self-hosted solution that tracks specific xpubs (rather than all addresses like Esplora does) and requires a full node.

Another much easier solution is to reject transactions with unconfirmed ancestors entirely. But it also means that you'll be rejecting a lot more transactions which could be reasonable to accept.

**Comment by wchance** [comment]
@shesek this is an amazing answer and everything explained makes sense.   One last question, which project will be easiest to work to find unconfirmed ancestors?

I will be installing the bwt since we have bitcoin node in network.

**Comment by shesek** [comment]
The information provided by bwt is based on bitcoind's [`getmempoolentry` rpc call](https://bitcoincore.org/en/doc/0.20.0/rpc/blockchain/getmempoolentry/), which you could also use directly. Check out the `bip125-replaceable`, `ancestorcount`, `ancestorsize` and `fees.ancestor` fields. The formula for calculating the effective fee rate based on these is `MIN(fees.ancestor/ancestorsize, own_fee/own_vsize)`.

**Comment by monzturreminem** [comment]
Double spending can be ok “if” (now pay close attention) you select all and share it adding to it something of value twice or more.so let’s just say I share it to my email and I decide to add a video to it and then I increase the quota the whole time I can add as many videos I want to it as far as the threshold goes for sending emails document what you did and see it on the chain as a whole new transaction with usually a way higher bitcoin total then you’ve ever seen with the original block that means that every block on the chain can be respect or re mined it usually stays the same height the date and time change but it can be done what you all are talking about is something that only a criminal thinks about so go ahead let them double spend the block. Won’t accept what they are trying to do but yes you can take a bitcoin total and totally stamp it on top of videos the rejuvenate the coin it holds you see you people aren’t seeing the light that’s right in front of you the more you spend the more that can be earned by mining spent transactions even tho it is spent it is still written this is digital money that means it’s allwAys money now there is a way to take a spent transaction and come up with a new nonce and create a whole new transaction out of old transactions but if you want the formula to the nonce you’ll have to ask me nicely over a glass of wine and smell good too females only lol this is who I am after all Eminem
And yes I made up Satoshi Nakamoto I wrote a new white paper called Satoshi Solutions and some curse word of a person trued having my IP address banned from wiki Intell you what being me is not easy everyone wants to try and piss me off but it’s cool no harsh feelings to all the haters out there just remember who gave you the intelligent and legal solution to your criminal little minds out there trying to solve how to double spend unfortunately I mean fortunately I open sourced it 4.0 so you have to give me credit and I will partner with anyone who does take on the white paper and my formulas I included even with old new debt all numbers in the negative and also I solved the $0.00 account to allow merchants to approve transactions on the second swipe and recover all costs plus nice guy rewards for being that merchant with their own ledger sheets that work at the zero level automatically the ledger goes negative and then in a mila second zeros itself out again the second swipe is just to show the transaction with a negative number now I have two transactions to work with on one ledger and if I have to explain why that is so cool then go back to the original white paper and solve it like I did and then you will know why it’s so cool especially cool working with negative numbers so come in now encourage spending no limit spending so I can put mine you all again shit I’m starting a business that pays people to spend my money just so I can get a recorded transaction the more you spend the more I earn so stop telling your kids no and stop trying to control their spending shit this is so far advanced that when the people who want you to be broke and poverty stricken shitting on the streets finally figure out there is no limits and everyone can have money for free they turn off the internet and then it’s over accept for what they want you to have so it’s a good thing the baby boomer are getting their behinds voted out of office and me the x generation born in 1972 is taking over with a new rhyme and a new style in which I say look at how I ended poverty and homelessness with one good day prayer and guidance. No actually it’s been a lifetime I’ve hated money and what it does to people just look at you all either trying to figure out how to spend already spent or trying to end accessibility to money that everyone needs to eat  remember what goes around comes around hate on me you get hated on by yourself cuz I simply just don’t hate other then when people say those people don’t deserve anything you have to earn it and I say did you choose to be born answer no you didn’t ask to be born in this hell or heaven depends but my point is we all have a right to unlimited supply to sustain life and if you think you don’t deserve privilege for just being born then there is something you should think about
Ok I’m done  oh and if anyone wants to donate to the marshallmathersfoundation@outlook.com
Private non profit and government affairs operations  feel free to I make sure the money goes where it’s supposed to oh an I was awarded 42 bitcoins when I solved the white paper if you can solve the new white paper I put out Satoshi solutions you’ll be able to acquire how ever many bitcoins you can. And other assets t. So don’t tell anyone but that’s what’s happening jack dorsey payed attention and you guy s are worried about double spending lol

Eminem

**Comment by monzturreminem** [comment]
Yes I can do consulting 2539299952 I am Satoshi solutions not sure if you asked me that question or not but I can get you thru anything and then some especially if you are a large Corp trying to secure large amounts of bitcoins

Eminem

**Comment by monzturreminem** [comment]
Safari - krßåñkbyßitcoin\kr:œkrœkrœpool.emoji\krßåñkr:\¥ŒDŒ\¥•10142020224.0000007


Eminem
