### ISSUE TITLE
[electrs] Feature Request: Add endpoint for querying txs by op_return

### ISSUE THREAD

**Issue by savudani8** [Blockstream/esplora#267]
It would be great to be able to have an endpoint such as `GET /opreturn/:hash256` that returns all transactions whose `op_return` output matches the `:hash256` parameter. Adding this feature would probably require either:
1. iterating through all transactions, or
2. storing an additional RocksDB object for transactions, indexed by the `op_return`

**Comment by shesek** [comment]
You can represent the `OP_RETURN` as a scripthash (`SHA256(scriptPubKey)`) and use the existing `GET /scripthash/:scripthash/txs` endpoint to get what you want.

**Comment by shesek** [comment]
Modifying the source code to make it index provably unspendable outputs is pretty straightforward though - you'll just need to remove the `is_spendable` check in [schema.rs:1075](https://github.com/Blockstream/electrs/blob/new-index/src/new_index/schema.rs#L1075) and [mempool.rs:386](https://github.com/Blockstream/electrs/blob/new-index/src/new_index/mempool.rs#L386), like so:

```diff
diff --git a/src/new_index/mempool.rs b/src/new_index/mempool.rs
index 16a771c..3acef9c 100644
--- a/src/new_index/mempool.rs
+++ b/src/new_index/mempool.rs
@@ -383,7 +383,6 @@ impl Mempool {
                 .output
                 .iter()
                 .enumerate()
-                .filter(|(_, txo)| is_spendable(txo))
                 .map(|(index, txo)| {
                     (
                         compute_script_hash(&txo.script_pubkey),
diff --git a/src/new_index/schema.rs b/src/new_index/schema.rs
index facc9f3..9014889 100644
--- a/src/new_index/schema.rs
+++ b/src/new_index/schema.rs
@@ -1072,7 +1072,7 @@ fn index_transaction(
     //      S{funding-txid:vout}{spending-txid:vin} → ""
     let txid = full_hash(&tx.txid()[..]);
     for (txo_index, txo) in tx.output.iter().enumerate() {
-        if is_spendable(txo) {
+        if true {
             let history = TxHistoryRow::new(
                 &txo.script_pubkey,
                 confirmed_height,
```

**Comment by savudani8** [comment]
Thanks for your quick reply @shesek! 

If I opened a PR for this feature would you be willing to merge it? This way I wouldn't have to deploy my own esplora service

**Comment by shesek** [comment]
If you make it configurable via a new CLI flag, something like `--index-unspendables`, I could consider merging it. But it probably wouldn't be enabled on the blockstream.info live production servers, because its somewhat of an exotic use-case that users don't typically need.
