### ISSUE TITLE
[Electrs] Add median time to block struct

### ISSUE THREAD

**Issue by monokh** [Blockstream/esplora#269]
`mediantime` is an essential field for timelock based applications. As opposed to the `timestamp` block field, it is not arbitrarily set by miners and is used as part of the consensus rules for verifying `OP_CHECKLOCKTIMEVERIFY`. `Bitcoind` rpc calls for `getblock` include this.

I believe it would need to be added in electrs and built into the "Block stats metadata" index?
Would you accept a PR for this?

**Comment by allenpiscitello** [comment]
Implemented in electrs. https://github.com/Blockstream/electrs/commit/78adcdb3504c61055aae8680220d680279a5ca0e

Will be deployed in next update to blockstream.info.

**Comment by shesek** [comment]
This is now deployed, available in [`GET /block/:hash`](https://github.com/Blockstream/esplora/blob/master/API.md#get-blockhash) as the `mediantime` field.
