### ISSUE TITLE
UI bug - Confidential Addresses Qr codes step over the header container

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [Blockstream/esplora#272]
# Desired behavior
- [ ] The Qr code is displayed within the colored container
- [ ] Using Green with a Liquid wallet, should allow scanning such Qr code when sending

<img width="1680" alt="Screen Shot 2020-11-09 at 4 57 07 PM" src="https://user-images.githubusercontent.com/22540533/98564395-9d143a80-22ac-11eb-97a1-97a09a9b4634.png">

# Actual behavior
- the Qr code for confidential addresses is larger and steps over the colored container, into the darker background
- example address https://blockstream.info/liquid/address/VJLCpZ8hvvCcmwz8doVqrd3bWRYJseXs5UykvNDGrXK175ovdNYzdQhzCkZz1Y5uc4KYmuNCgNKUDakx

<img width="1680" alt="Screen Shot 2020-11-09 at 4 57 28 PM" src="https://user-images.githubusercontent.com/22540533/98564430-aa312980-22ac-11eb-9fa6-c25f10e894aa.png">

**Comment by alessandro-saglimbeni** [comment]
The UI bug seems still persistent after https://github.com/Blockstream/esplora/pull/277 this is even more visible on mobile
<img width="500" alt="Screen Shot 2020-11-19 at 11 15 47 PM" src="https://user-images.githubusercontent.com/22540533/99730789-50efa400-2abd-11eb-88c2-4c8d3ac2f9cb.png">

<img width="250" alt="Screen Shot 2020-11-19 at 11 15 47 PM" src="https://user-images.githubusercontent.com/22540533/99730997-83010600-2abd-11eb-8a8d-ca97b23980a3.png">

**Comment by shesek** [comment]
@alessandro-saglimbeni The changes in #277 aren't yet deployed on the live server.

**Comment by escapedcat** [comment]
Seems to fixed now:  
<img width="250" src="https://user-images.githubusercontent.com/1016218/149060757-6ba071e0-3221-4e09-ac03-dfcfb5d9ee54.png"/>

Can be closed I guess
