### ISSUE TITLE
Question about unspents

### ISSUE THREAD

**Issue by idoor88** [Blockstream/esplora#279]
Hi, I have a question about unspent transactions, I used the following query:
GET /address/:address/utxo
https://blockstream.info/api/address/18HLJ9miBraVz4REwyShpYqWPyWMLifzqm/utxo
The result shows two records, each has a value field, each transaction is already confirmed, the first has a value of 25322382, the second has a value of 546, does that mean the number 546 is the final remaining amount of unspent? and the second transaction spent amount of 25322382 minus 546? 

Thanks

This is the result of above query:
[{"txid":"693bfd4d7394bd66abf4fed2fbf557d03fa2c2d91c694583528a4547b705928f","vout":2,"status":{"confirmed":true,"block_height":644645,"block_hash":"00000000000000000005377489de8162d58142e7ba34d7e42abda2b9b3bc89fa","block_time":1597982277},"value":25322382},{"txid":"12eaa8594265f57b6968adf79d0831f7c61c831d81d1edfd9f100c38c09d3e24","vout":0,"status":{"confirmed":true,"block_height":655190,"block_hash":"0000000000000000000d6a44b46922ebf506f4fb1b9d7914ad3d02f9d5e24c62","block_time":1604386804},"value":546}]

**Comment by shesek** [comment]
Each record in the utxo list represent one unspent output of a certain amount. Spent funds will not show up in this list at all. To get the current balance of the address, you simply need to sum all the `value`s of all the utxos together.

I'm closing this to keep things organized, but please do feel free to ask back if you have more questions.
