### ISSUE TITLE
How to tell docker to use local bitcoind instance

### ISSUE THREAD

**Issue by th3geek** [Blockstream/esplora#280]
Hi,

Pardon me if this has already been asked, but I couldn't seem to find the answer from the searching...

I'm trying to run to just run the plain ole "explorer for Bitcoin mainnet": 
```
docker run -p 50001:50001 -p 8080:80 \
           --volume $PWD/data_bitcoin_mainnet:/data \
           --rm -i -t esplora \
           bash -c "/srv/explorer/run.sh bitcoin-mainnet explorer"
```
and I would like to avoid needing to re-download and index the whole blockchain since I already have a bitcoind instance running locally. Is there some command line option (-e) I can tell docker to just use my local bitcoind instance? If not, would I be able to just point it to use my current bitcoind data directory with the --volume argument? It seems like there would be problems if two instances of bitcoind are trying to use the same data files at the same time? Maybe it would make sense to just kill my local bitcoind and let the docker image use the data directory? I'm pretty sure I have all the proper options set for my bitcoind (txindex=1, etc...). Any suggestions?

Thanks...

edit: Since I'm asking questions, I figure i'd throw this one out too: I'm assuming that electrs is required, but I'm also running a local instance of electrumx... Any chance I could tell esplora to use that instead of electrs?

**Comment by th3geek** [comment]
Umm. If the sync is stopped for any reason, re-running the docker command in my original post, it causes bitcoind to start re-syncing from scratch? Its a real bummer, since its had been running for the better part of a day and now it's gotta start all over again? am I missing something? What command should I use to make it start back where it left off?

**Comment by shesek** [comment]
The docker setup does not make it easy to use an existing full node. I would recommend setting up esplora/electrs separately, without using docker, which isn't too hard. I wrote some instructions for doing this [here](https://bitcoin.stackexchange.com/questions/91746/configure-esplora-to-point-to-the-bitcoind-servers-ip-address/91859#91859).

But if you do choose to use docker, the `--volume $PWD/data_bitcoin_mainnet:/data` argument will mount a directory form your host into `/data`, which will be used to persist all the data. So nothing should get lost if you restart.

> edit: Since I'm asking questions, I figure i'd throw this one out too: I'm assuming that electrs is required, but I'm also running a local instance of electrumx... Any chance I could tell esplora to use that instead of electrs?

I'm afraid that this is not possible.
