### ISSUE TITLE
connect esplora docker container to bitcoind running on host

### ISSUE THREAD

**Issue by pox** [Blockstream/esplora#297]
Apologies if this isn't the right medium to ask usage questions (if so, where should I?)

I have bitcoind running locally and also `Blockstream/electrs` connected to it. How do I tell the dockerized version of esplora to connect to electrs instead of trying to sync the entire blockchain on its own? Or at least how do I tell it to sync the blocks from the local bitcoind?

Essentially what I don't understand is if I'm supposed to run both electrs and esplora (as the GUI), or whether esplora contains the electrs server itself, in which case I just need to figure out how to tell it to connect to bitcoind...

**Comment by shesek** [comment]
I'm afraid that using the dockerized epslora with an existing bitcoind/electrs instance is not currently possible.

I wrote a walkthrough for setting things up without docker, which you might find useful: https://bitcoin.stackexchange.com/a/91859

**Comment by pox** [comment]
Thanks @shesek 
Great guide, btw. Looks very simple.
