### ISSUE TITLE
Feature Request: Expose 'Assets' section on Liquid's landing page

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [Blockstream/esplora#310]
### Requirements
Add a tab section in https://blockstream.info/liquid/ called `Assets` peer to the [`Blocks`](https://blockstream.info/liquid/) and [`Transactions`](https://blockstream.info/liquid/tx/recent) sections.

Such section should link to https://blockstream.info/liquid/assets/

### Reference screenshot
<img width="900" alt="Screen Shot 2021-04-26 at 8 01 37 PM" src="https://user-images.githubusercontent.com/22540533/116129806-d14cad80-a6ca-11eb-8b46-3ed36771c391.png">

**Comment by allenpiscitello** [comment]
This is now done and can be closed.
