### ISSUE TITLE
Taproot output type

### ISSUE THREAD

**Issue by Sjors** [Blockstream/esplora#314]
These are currently not recognized, see e.g. the first output of this Signet transaction: https://explorer.bc-2.jp/tx/b3a4cf9cf5a03232ab764869d4024d7c4cc7814c0725f4280b7218a2dd5fa07f?expand

<img width="449" alt="Schermafbeelding 2021-05-22 om 14 40 45" src="https://user-images.githubusercontent.com/10217/119226896-b58ec880-bb0b-11eb-8bff-7ae9b254af2f.png">

cc @kallewoof

**Comment by druonn** [comment]
I have the same problem,
with:
https://hub.docker.com/r/blockstream/esplora/tags
https://github.com/Blockstream/esplora/blob/master/Dockerfile

**Comment by druonn** [comment]
Date 3 January 2022

**Comment by druonn** [comment]
Maybe taproot update is only on the site https://blockstream.info/. There is another problem, the shown address is different from the real address (the last characters are different).

**Comment by druonn** [comment]
TX: ae99cbda838221d7912402a118eb4f1d56db07de6051c7aeb056db4303bb45ff

in [blockstream](https://blockstream.info/tx/ae99cbda838221d7912402a118eb4f1d56db07de6051c7aeb056db4303bb45ff) (v1_p2tr) PREVIOUS OUTPUT ADDRESS 
bc1p53tapspendyea5kl2uwkz2a9fxh87xvnslkuatqhtxvjzrm25wwsktfwpg
in [localhost] (unknown) PREVIOUS OUTPUT ADDRESS 
bc1p53tapspendyea5kl2uwkz2a9fxh87xvnslkuatqhtxvjzrm25wwsrhezy2
in [blockchain] (https://www.blockchain.com/btc/tx/ae99cbda838221d7912402a118eb4f1d56db07de6051c7aeb056db4303bb45ff)

**Comment by shesek** [comment]
@druonn the code running on blockstream.info matches this repo's master.

But it seems like the `blockstream/esplora:latest` image on Docker Hub is outdated, can you try [building it locally](https://github.com/Blockstream/esplora#how-to-build-the-docker-image) and see if that makes a difference?

**Comment by druonn** [comment]
The same result:

- from blockstream
43cecb1238d249927a72842967348c288f7b2bdf5904aa820eaa3c1e45a90942	
fa3bde9d1d1da17dbf3390c3367691f033ec1e495cf00e528e9fe11c1ec87eae:2
0.0025 BTC
**bc1ptce2r3j8fr0e65a7wfvu7qj8zzvhpzv3fuaagn0d6mfezuksspssxgn02d**
0.00128989 BTC
bc1qhnllmcx6ucymf2pulpwq8aehsqyhw9zqsnskhsyymc9y8nzp4wtqs3hjht
0.00120802 BTC

- from locally build
43cecb1238d249927a72842967348c288f7b2bdf5904aa820eaa3c1e45a90942	
fa3bde9d1d1da17dbf3390c3367691f033ec1e495cf00e528e9fe11c1ec87eae:2
0.0025 BTC
**bc1ptce2r3j8fr0e65a7wfvu7qj8zzvhpzv3fuaagn0d6mfezuksspssn5rr00**
0.00128989 BTC
bc1qhnllmcx6ucymf2pulpwq8aehsqyhw9zqsnskhsyymc9y8nzp4wtqs3hjht
0.00120802 BTC

**Comment by shesek** [comment]
@druonn To be clear, you need to rebuild both the `blockstream/esplora:latest` and the `esplora` images, like so:

```
$ docker build -t blockstream/esplora-base:latest -f Dockerfile.deps .
$ docker build -t esplora .
```

Is that what you did?

**Comment by Soundpisey** [comment]
I have seen it. Thank you very much.
+85577922321 . telegram

**Comment by Soundpisey** [comment]
No, I do not know. Sorry for any inconvenience.

**Comment by druonn** [comment]
@shesek 

After fully locally build (how you mention it) is working correctly.

Thanks!

**Comment by shesek** [comment]
@druonn Great, thank you for confirming!

@greenaddress can we get the current master built and published to docker hub?
