### ISSUE TITLE
Broadcast endpoint

### ISSUE THREAD

**Issue by tiero** [Blockstream/esplora#32]
Do you think there will be a possibility to add such feature with current live infrastructure? Both for Bitcoin and in particular Liquid

**Comment by shesek** [comment]
This is upcoming in the next release: https://github.com/shesek/electrs/commit/1b85305f16b520511f8df94bace928b75d47740c

**Comment by tiero** [comment]
> This is upcoming in the next release: [shesek/electrs@1b85305](https://github.com/shesek/electrs/commit/1b85305f16b520511f8df94bace928b75d47740c)

Awesome!

**Comment by greenaddress** [comment]
this is now merged and deployed - thanks! closing
