### ISSUE TITLE
Bech32m support

### ISSUE THREAD

**Issue by Sjors** [Blockstream/esplora#323]
Currently SegWit 1 (Taproot) addresses are displayed as bech32 rather than [bech32m](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki).

Example: https://explorer.bc-2.jp/tx/95c7feca5f9e31a06d6391fecbeb13280b3da97cf6135d19c18db282b86cac9e

The bech32m address tb1p74334dv2yy92x564xucd8x0rv6h2v65djj8j8mjg26fam204ud4qkuvean there is displayed as tb1p74334dv2yy92x564xucd8x0rv6h2v65djj8j8mjg26fam204ud4qrqu4c3. 

```
src/bitcoin-cli -signet validateaddress tb1p74334dv2yy92x564xucd8x0rv6h2v65djj8j8mjg26fam204ud4qrqu4c3
{
  "isvalid": false,
  "error": "Version 1+ witness address must use Bech32m checksum"
}
```

**Comment by RCasatta** [comment]
Come here to open this issue, I see esplora fork https://github.com/Blockstream/esplora/ is using rust-bitcoin 0.23 while to support bech32m I think it's needed 0.26.2

**Comment by jaonoctus** [comment]
looking forward for this solution

**Comment by shesek** [comment]
We have [a branch](https://github.com/Blockstream/electrs/commits/202108-deps-signet) with rust-bitcoin v0.27 that's undergoing QA and should be merged soon, iiuc bech32m should Just Work once that's in.

**Comment by shesek** [comment]
@druonn the changes in the branch I mentioned were since merged and are now part of master.
