### ISSUE TITLE
More Reliable Tor Hidden Service Config Suggestion

### ISSUE THREAD

**Issue by nopara73** [Blockstream/esplora#36]
You are a public company, so you don't need to hide your location, thus you are in a position to provide a faster, more stable and more reliable Tor hidden service than other services with the following configuration options:

```
# ---MAKE TOR FASTER---

# Need to disable for HiddenServiceNonAnonymousMode
SOCKSPort 0
# Need to enable for HiddenServiceSingleHopMode
HiddenServiceNonAnonymousMode 1
# This option makes every hidden service instance hosted by a tor
# instance a Single Onion Service. One-hop circuits make Single Onion
# servers easily locatable, but clients remain location-anonymous.
HiddenServiceSingleHopMode 1
```

**Comment by greenaddress** [comment]
@nopara73 thank you good idea, we already used in other occasions but not for the explorer - added a PR here https://github.com/Blockstream/esplora/pull/37 for review

**Comment by greenaddress** [comment]
@nopara73 try now :)

**Comment by nopara73** [comment]
That was quick :)

**Comment by greenaddress** [comment]
this should all be deployed correctly too as far as I can see and seems to work well. Thanks again! Closing.
