### ISSUE TITLE
Web page doesn't work without cookies

### ISSUE THREAD

**Issue by stevenroose** [Blockstream/esplora#366]
I vaguely recall already having mentioned this in private communication.

But if you configure Firefox to not support any cookies, the blockstream.info instance of esplora just turns into a white page. This happens to lots of news websites, so I suspect it's due to some kind of dependency that many websites include. But for esplora, that should definitely not be the case.

**Comment by shesek** [comment]
Esplora doesn't use cookies, but it appears that blocking cookies on Firefox also blocks `localStorage`, which is used by Esplora to persist the language/theme selection. I sent #368 to make localStorage optional, which resolves this issue (tested on Firefox with cookies blocked).

**Comment by stevenroose** [comment]
Hmm, curious. But I guess that makes sense. And yeah doesn't make sense
that it wouldn't work without theme selection caching. Thanks for the fix!

**Comment by shesek** [comment]
As a workaround until the fix gets deployed, it is also possible to use the noscript version at https://blockstream.info/nojs
