### ISSUE TITLE
Can we add an ID to the transaction details so you can anchor links directly to it?

### ISSUE THREAD

**Issue by pedromvpg** [Blockstream/esplora#38]
Can we add an ID to the transaction details so you can anchor links directly to it? Its great to have an argument to have the detail expanded on landing but it would be great to just land on that point of the scroll too.

![screenshot at feb 19 20-29-15](https://user-images.githubusercontent.com/807505/53059558-39692e80-3485-11e9-9c9d-8b12d5802e01.png)

**Comment by greenaddress** [comment]
@pedromvpg we merged the feature request and deployed it so you should be able to use it now! thank you for the request!
