### ISSUE TITLE
Can the theme be defined as an url parameter.

### ISSUE THREAD

**Issue by pedromvpg** [Blockstream/esplora#39]
Like so https://blockstream.info/tx/4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b?expand&theme=light

**Comment by shesek** [comment]
This is currently only supported in the noscript version of the explorer: https://blockstream.info/nojs/tx/4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b?expand&theme=light

What'e the user-case for this?

**Comment by shesek** [comment]
Closing for now, report back with some more details and I'll reopen :)
