### ISSUE TITLE
Block Timestamp Language Doesn't Change

### ISSUE THREAD

**Issue by MarioGibney** [Blockstream/esplora#41]
It seems that the timestamp for blocks is always displayed in OS language. It's always English for me, even when I select a different language, and our translator noticed that it's always Korean for him, even when he selects Japanese.

![image](https://user-images.githubusercontent.com/22239865/53316843-3c499200-387e-11e9-8f82-a773ef2946ec.png)

**Comment by shesek** [comment]
I can't seem to reproduce this. What OS/browser are you using?

![peek 2019-02-25 18-50](https://user-images.githubusercontent.com/877904/53353830-390ddf00-392e-11e9-91c4-9b3f4817e5ef.gif)

**Comment by MarioGibney** [comment]
I'm not able to produce it now. It was an older issue I just moved over from the gitlab, so perhaps not a problem anymore.
