### ISSUE TITLE
`broadcast?tx=<rawhex>` endpoint does not return CORS headers

### ISSUE THREAD

**Issue by pinheadmz** [Blockstream/esplora#42]
I'm not sure if this is intentional for some reason, but other endpoints like `address/:address/txs` return data with `access-control-allow-origin: *` headers. The `broadcast` endpoint does not.

**Comment by greenaddress** [comment]
@pinheadmz was that the normal url or the nojs variant?

**Comment by pinheadmz** [comment]
Looks like this just affects error messages. A successful broadcast will get a txid returned, with CORS. But broadcast failure messages are returned 400 with no CORS

**Comment by greenaddress** [comment]
@pinheadmz this is fixed in master 2aae5836c38f5b65797f1c3c4ed4cd0d7ff20ba5

Next time we deploy it should be fixed in the live instance as well.

**Comment by greenaddress** [comment]
closing
