### ISSUE TITLE
enable tls?

### ISSUE THREAD

**Issue by matthiasdebernardini** [Blockstream/esplora#463]
I want to connect to electrum server securely, I dont see the option for doing that. Is it supported?

**Comment by shesek** [comment]
Both the HTTP and Electrum servers do not have built-in support for TLS.

For a public setup, it is expected to have a separate TLS terminating reverse proxy running in front of the Esplora servers.

For a private setup, you may also consider using SSH tunnels, a VPN or Tor Onion as an encryption/authentication layer.
