### ISSUE TITLE
endpoint does not exist "/mempool/recent"

### ISSUE THREAD

**Issue by Kexkey** [Blockstream/esplora#48]
Hi, I just upgraded esplora to the latest version.  When clicking on the "Transactions" tab, I am getting this message.

blockstream.info works as expected though.  I just rebuilt the esplora container as documented.

Thanks!

**Comment by greenaddress** [comment]
@Kexkey  Are you sure you are not connecting to an old instance or maybe some kind of cache?

**Comment by Kexkey** [comment]
I stopped the esplora container, deleted all the Docker images (the esplora one as well as all the intermediary (cache) ones) to make sure no cached images were used and rebuilt it.  I get the ame error.

In `logs/electrs-bitcoin.log` I can see:

```
2019-03-06T20:22:19.182+00:00 - WARN - HttpError(404, "endpoint does not exist \"/mempool/recent\"")
```

as well as `endpoint does not exist "/mempool/recent"` in the web page when accessing `https://explorer.kexkey.com/tx/recent`.

I'll try to dig a little more to understand what's going on.

**Comment by Kexkey** [comment]
Oh!  I just found the "blockstream/esplora-base" image locally that's 2 weeks old that I didn't delete!  Pretty sure that's the problem.  BRB in a few minutes.  :)

**Comment by Kexkey** [comment]
Ok that was it.

Suggestion: avoid using "latest" tag on Docker images.  It is a known problem, that tag is nothing more than a regular string and is not a reference to the actual latest image.  I had to face all sort of problems myself when publishing new releases when I was using that tag.  In this case, I had locally the "blockstream/esplora-base:latest" image from 2 weeks ago.  Docker dumbly used it instead of downloading the new "latest" tag since it doesn't know it's not the same image (it doesn't compare the hash/digests).

So you got a good call when you suggested to have a look at any caches on my side!  :)  Thanks again!

**Comment by greenaddress** [comment]
I always rebuild both which is a no op when not needed. I suggest you use that too in your scripts but we should make it more obvious on the README too!
