### ISSUE TITLE
Chain logo not shown in TOR Browser

### ISSUE THREAD

**Issue by sgeisler** [Blockstream/esplora#49]
With high security settings the TOR Browser blocks SVG images. That leads to the bitcoin/liquid logo not being shown:

![2019-03-06-144123_9600x2160_scrot](https://user-images.githubusercontent.com/1876998/53919160-0181ef80-401e-11e9-8653-72726e0bc079.png)

Maybe use a png image for the `nojs` version?

**Comment by greenaddress** [comment]
will look into it, thank you for raising this!

**Comment by shesek** [comment]
Fixed by https://github.com/Blockstream/esplora/commit/f93492f0ea9cb4de4908be7eeb24dcf3c5d10256, thanks for the report!
