### ISSUE TITLE
Empty search results page is empty

### ISSUE THREAD

**Issue by abrkn** [Blockstream/esplora#63]
![image](https://user-images.githubusercontent.com/843958/55396314-cff13b00-556d-11e9-94f1-96b1ad156b34.png)

Repeat search field on the page or add link back to search if lazy

**Comment by shesek** [comment]
Fixed in https://github.com/Blockstream/esplora/commit/db91d9b5cbd7b56f8c18842ac5adf8a378f687c2, thanks!
