### ISSUE TITLE
Empty search results page does not update browser address bar

### ISSUE THREAD

**Issue by abrkn** [Blockstream/esplora#64]
![28460313bc91756436ed40d0f81d8175](https://user-images.githubusercontent.com/843958/55396654-9b31b380-556e-11e9-870f-bd226178ee68.gif)

Push an url such as `https://blockstream.info/search?q=mememagic`, to navigation history. Would improve back/forward-button user experience.

**Comment by shesek** [comment]
Implemented in https://github.com/Blockstream/esplora/commit/be372c30ab8bf57f344a7be4d77a84fdf5bb4a1e. Thanks for the suggestion @abrkn!
