### ISSUE TITLE
Liquid pegouts not decoded in explorer.

### ISSUE THREAD

**Issue by roconnor-blockstream** [Blockstream/esplora#65]
Output 1 of https://blockstream.info/liquid/tx/3fe0239f003127e294dd8aad10a91da4998084859159907f90c984823021c1cb is a pegout, but isn't labeled as such.  Similarly @ https://blockstream.info/liquid/api/tx/3fe0239f003127e294dd8aad10a91da4998084859159907f90c984823021c1cb the output 1 lists `
pegout: null` even though it is one.

**Comment by shesek** [comment]
This appears to be a regression related to the recent updates to the latest rust-bitcoin and bitcoin_hashes and some changes that were made to the way endianness is handled. Working on a fix.

**Comment by shesek** [comment]
Should be fixed by 712e6604611f04c7b14a1b041ee5f30ece30d12c (not live yet, will go up with the next deployment)

**Comment by shesek** [comment]
The fix is now live, might require a hard refresh (Ctrl-shift-r) to see it.

**Comment by roconnor-blockstream** [comment]
I don't know if I should reopen this, but the output numbering for https://blockstream.info/liquid/tx/3fe0239f003127e294dd8aad10a91da4998084859159907f90c984823021c1cb is incorrect.

**Comment by shesek** [comment]
I created #80 to keep track of that.
