### ISSUE TITLE
ETA is unavailable, but mempool depth is not shown

### ISSUE THREAD

**Issue by MarcoFalke** [Blockstream/esplora#66]
The mempool depth should be shown for interested users regardless of whether the ETA (confEstimate) is available.

Relevant code:
https://github.com/Blockstream/esplora/blob/258cf209993d45f7807ae9d1c86eba6722acc5dd/client/src/views/tx.js#L117

**Comment by shesek** [comment]
Changed in dd7023537615016e1bec348eb6b848cb75b61509, thanks for the suggestion!
