### ISSUE TITLE
Ambiguous thousands separator

### ISSUE THREAD

**Issue by real-or-random** [Blockstream/esplora#67]
Currently we use "." as a decimal separator and "," as thousands separator, no matter what the language is. This is confusing for users depending on their culture, see https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use. For example I read the output amount in https://blockstream.info/tx/f21e747078c67e6c6445d7ca7145a28cc72567b12bd82904ed8ef9b51ea46255 as "1.2", not as "1200" because I'm German. It's even more confusing for numbers where we don't have decimal points, e.g., transaction weight or size.

I propose to switch to use a non-breaking space as a thousands separator and keep "." as decimal separator, again no matter what the language is. This is hard to misunderstand for anybody, is the SI-style and confirms to an ISO standard, see https://en.wikipedia.org/wiki/Decimal_separator#Current_standards.

**Comment by real-or-random** [comment]
Ah I just see that this was only recently changed in https://github.com/Blockstream/esplora/commit/f17f9dadbe8723287eef090af3fcaf1b5bb0dcbe. I'm interested in your reasoning, I'm not sure it was a good change.

**Comment by shesek** [comment]
I agree, this is confusing. I didn't consider internationalization enough when I implemented this.

We could either go with your suggestion of using a non-breaking space as separator, or introduce a locale-aware thousands separator (and I guess, while at it, also for the decimal separator, which is "," in some languages). @greenaddress thoughts?

**Comment by real-or-random** [comment]
I think the main confusion stems from the fact that we use "," and "." at the same time. Whenever we switch to a space for the thousands separator, things will be fine. 

One point against locale-aware separators is that we currently have a possibility to select the language manually but language != other locale settings. So we couldn't use the actual user locale but would need to make it dependent on selected language.

**Comment by shesek** [comment]
Implemented in 141d4ea11c28703ab07f30465d546687231cc6c1 and 72bc0e68377b77692d1a76dc5eeb14f1ff602d64, using a thin space (`U+202F`, "NARROW NO-BREAK SPACE") as the thousands separator, as [recommended by SI](https://www.bipm.org/en/publications/si-brochure/section5-3-4.html). I also made it only add the separator when there are 5 or more non-decimal digits.
