### ISSUE TITLE
Local timestamp reporting.

### ISSUE THREAD

**Issue by AUAggy** [Blockstream/esplora#72]
While my Bitcoin full node reports the time in "2019-04-16T11:05:17Z" format.
Esplora detects my timezone and reports the timestamp of local region.
Could we have an option to toggle Esplora timezone on/off?

**Comment by shesek** [comment]
You can get the times in UTC if you go to the [nojs version](https://blockstream.info/nojs/) of the explorer.

**Comment by AUAggy** [comment]
Works great. Thanks.
Suggestion: Maybe include an entry in [README.md](https://github.com/Blockstream/esplora/blob/258cf209993d45f7807ae9d1c86eba6722acc5dd/README.md) referencing this?
