### ISSUE TITLE
Show redeem script ASM for P2SH transactions

### ISSUE THREAD

**Issue by moneyball** [Blockstream/esplora#73]
The redeem script is embedded in the SCRIPTSIG. Here is an example: https://blockstream.info/tx/726667f35caf1a26d6de44f03c87632bd2b271270ca26430f2eab4c4b4a32bff?expand

It should be possible to parse "52210399eb2157e72efb63e6eebc232fd9b247f1aaad0767a194a699a127289eddccb421020f7017d179b1b26933ccbaf5b0627ec99f54564ab0477a54143ae53f307133ef52ae" out of that SCRIPTSIG and display it separately as a redeem script (ASM).

This would greatly aid beginners learning how Bitcoin works, and also be more convenient for experts.

@harding @sipa

**Comment by sipa** [comment]
Likewise for P2WSH, where the last witness stack elements could be shown as a disassembled script.

**Comment by shesek** [comment]
Thanks for the suggestion! Implemented in https://github.com/Blockstream/electrs/commit/5cd986896a7e7039a3f929ba9cd63ee1d05cef4f and https://github.com/Blockstream/esplora/commit/cad3cef99b1a149193e7f02bf515bbdc9851a91e, both for P2SH redeem scripts and for P2WSH witness scripts.

This is how a P2SH-P2WSH spend looks like:

![image](https://user-images.githubusercontent.com/877904/56709428-f13ae680-6729-11e9-8028-624ea243a92c.png)

**Comment by moneyball** [comment]
Thank you for the quick turnaround! Looks great. I am not familiar with the
development / build / release process for blockstream.info. Is it the case
that the next release will automatically pick up this change? Or, do I need
to file a separate issue for that specific service?

**Comment by shesek** [comment]
The next release will include this change.
