### ISSUE TITLE
blech32 addresses shown as bech32 mainchain "bc" addresses

### ISSUE THREAD

**Issue by domegabri** [Blockstream/esplora#79]
blech32 addresses can be generated in elements0.17

explorers shows them as bech32 main chain addresses

example:

https://blockstream.info/liquid/tx/feb5eb773c08e61515ebdf035e424a8f5b1b281e7a6b848f977de785928b0502

**Comment by shesek** [comment]
Fixed by https://github.com/shesek/electrs/commit/67a2fa3475f20776d9305767763d9fd2812d7c9d. Thanks for the bug report!

**Comment by shesek** [comment]
Related followup work: https://github.com/Blockstream/esplora/issues/82
