### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by lclc** [Blockstream/esplora#84]
A websocket for getting notification about new transactions on a specific address would be nice (similar to https://www.blockchain.com/api/api_websocket).

I guess this issue should go into the electrs-repo, but that repo doesn't have issues activated.

**Comment by lclc** [comment]
Actually, a maybe better option for the notification API would be support for Server Sent Events (SSE) with something like https://docs.rs/eventsource/0.3.0/eventsource.

**Comment by alexiskattan** [comment]
@lclc did you ever hear anything about this?

**Comment by shesek** [comment]
Push notifications would be great to have, but its not currently prioritized.

For a self-hosted solution for tracking your wallet addresses, you might want to try [bwt](https://github.com/bwt-dev/bwt) which supports [Server-Sent-Events](https://github.com/bwt-dev/bwt#server-sent-events) as well as [web hooks](https://github.com/bwt-dev/bwt#web-hooks).

**Comment by shesek** [comment]
#364 adds support for accessing the Electrum RPC server over WebSockets. It is currently still unmerged (and not available on blockstream.info) but should work.
