### ISSUE TITLE
Not a issue but is a question

### ISSUE THREAD

**Issue by vincenzopalazzo** [Blockstream/esplora#86]
Hi,

I have a question for the esplora, this framework extract also the id wallet Input and id wallet output?

**Comment by shesek** [comment]
I'm not sure I understand the question, what do you mean by id wallet?

**Comment by vincenzopalazzo** [comment]
@shesek Sorry for my terrible english
 
I can give you an example:
This is a raw [transaction id](https://www.blockchain.com/it/btc/block/00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048) and your project esplora find the information of the wallet [into raw transaction](https://www.blockchain.com/it/btc/tx/0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098).
In other words, the esplora find the destination wallet?

> 12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX
