### ISSUE TITLE
fee-estimate api returns confirmation target as string and not numeric as api doc suggests

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/esplora#87]
This: https://github.com/Blockstream/esplora/blob/master/API.md#fee-estimates

Says that the results of /api/fee-estimates is of the format:

{ 2: 36.183, 3: 34.841, 4: 34.841, 6: 34.841, 10: 22.164, 20: 9.692, 144: 1, 501: 1, 1008:1 }

When the actual output is: 

{"144":1.0,"1008":1.0,"4":32.934,"2":62.769,"10":24.383,"20":1.077,"3":59.354,"504":1.0,"6":25.608}

It would be better to have it as numeric as the documentation suggests as the results could be ordered easier.

**Comment by wintercooled** [comment]
Raised Pull Request #97

**Comment by shesek** [comment]
Closed in favor of #97
