### ISSUE TITLE
get-mempool api returns decimal for fee_histogram's feerate but documentation suggests int

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/esplora#88]
https://github.com/Blockstream/esplora/blob/master/API.md#get-mempool

Shows example output as: 

"fee_histogram": [[53, 102131], [38, 110990], [34, 138976], [24, 112619], [3, 246346], [2, 239701], [1, 775272]]

When actually it is:

[[64.28445,50088], ... ,[1.0,23247]]

**Comment by shesek** [comment]
The example is not consistent with the API, it should be returned as decimals. I'll update the docs.

**Comment by shesek** [comment]
I wanted to put in a real example, but its quite lengthy... ended up adding some decimals to the existing examples instead (https://github.com/Blockstream/esplora/commit/e5ad4868ee3bf76be51d6655a97560ca19cb6d24).
