### ISSUE TITLE
Display Issued Assets amount without decimal (at satoshi level)

### ISSUE THREAD

**Issue by allenpiscitello** [Blockstream/esplora#89]
The issued assets are generally going to be whole number values, and should display as this, it can be confusing when this differs from other tools and the concept of a satoshi must now be explained.

**Comment by shesek** [comment]
This was done in the [wip assets branch](https://github.com/shesek/esplora/commits/201905-assets) (the default precision is 0 decimal digits, unless overriden by the issuer), which should get merged to master soon-ish.
