### ISSUE TITLE
Cannot get electrs to listen on HTTP REST port

### ISSUE THREAD

**Issue by tinova** [Blockstream/esplora#90]
I compiled electrs and I'm trying to get it to listen on the HTTP REST post.

Configuration of electrs and launch command:

 https://gist.github.com/tinova/b701c37bcb395f2131b5289a55b8539a

There it claims to be listening on http_addr: V4(127.0.0.1:3000). However, I cannot telnet to it, and apparently it is not really listening there

```
[tinova@alpha electrs]$ ss -untap|grep elect
tcp    LISTEN      0       0            127.0.0.1:4224            0.0.0.0:*      users:(("electrs",pid=29038,fd=5))
tcp    CLOSE-WAIT  1       0            127.0.0.1:55668         127.0.0.1:8332   users:(("electrs",pid=29038,fd=1658),("electrs",pid=29038,fd=1657))
tcp    CLOSE-WAIT  1       0            127.0.0.1:54494         127.0.0.1:8332   users:(("electrs",pid=29038,fd=1642),("electrs",pid=29038,fd=1641))
tcp    CLOSE-WAIT  1       0            127.0.0.1:54226         127.0.0.1:8332   users:(("electrs",pid=29038,fd=7),("electrs",pid=29038,fd=6))
```

How can i further debug this? Any more info I can provide I'd be happy to.

**Comment by shesek** [comment]
It looks like its still indexing blocks. Has there been progress since you posted this issue?

Also, it seems like its loading blocks using the RPC and not from the `.blk` files, probably because a previous run of the indexer was interrupted (it doesn't have to be like that, created #91 to keep track of that). It's probably not worth doing that by now, but you could remove the db directory to get the indexing to start over using the blk files.

**Comment by tinova** [comment]
Hi shasek, thanks for your answer. Indeed it was still indexing using the RPC, I've deleted the db directory as per your suggestion and now it is using the .blk files. Thanks for opening #91.

It looks like it read everything, compacted RocksDB and then started again with the .blk files at a slower pace. I'll keep an eye on it, restart if needed and come back with an update. 

```
TRACE - fetched 51 blocks
DEBUG - writing 512346 rows to RocksDB { path: "./db/mainnet/newindex/txstore" }, flush=Disable
DEBUG - starting full compaction on RocksDB { path: "./db/mainnet/newindex/txstore" }
DEBUG - finished full compaction on RocksDB { path: "./db/mainnet/newindex/txstore" }
DEBUG - indexing history from 578004 blocks using BlkFiles
DEBUG - listing block files at "/home/tinova/.bitcoin/blocks/blk*.dat"
TRACE - reading "/home/tinova/.bitcoin/blocks/blk00000.dat"
TRACE - parsing 134217691 bytes
TRACE - reading "/home/tinova/.bitcoin/blocks/blk00001.dat"
TRACE - fetched 119968 blocks
TRACE - parsing 134212465 bytes
```

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
