### ISSUE TITLE
multiple addresses API

### ISSUE THREAD

**Issue by isghe** [Blockstream/esplora#92]
Hi, Do we have any plans to add APIs in POST, to query multiple addresses?
```
POST addresses/utxos
POST addresses/txs
POST scripthash/utxos
POST scripthash/txs
```
so it will be possible to:
`$ curl --header 'Content-Type: application/json' --data-binary '{"addresses": ["2MvknKexQHJdRpfwL6AFFo2nh6tireuFY1L", "2NF4MTenSS3Hp7NqjFDP22Bqq3CSQUjxEfp"]}' https://blockstream.info/testnet/api/addresses/txs`

Thanks, Isidoro

EDIT: I see right know the also the https://github.com/Blockstream/esplora/issues/27 is asking the same

**Comment by shesek** [comment]
Closing in favor of #27.

**Comment by Elfikan** [comment]
> Hi, Do we have any plans to add APIs in POST, to query multiple addresses?
> 
> ```
> POST addresses/utxos
> POST addresses/txs
> POST scripthash/utxos
> POST scripthash/txs
> ```
> 
> so it will be possible to:
> `$ curl --header 'Content-Type: application/json' --data-binary '{"addresses": ["2MvknKexQHJdRpfwL6AFFo2nh6tireuFY1L", "2NF4MTenSS3Hp7NqjFDP22Bqq3CSQUjxEfp"]}' https://blockstream.info/testnet/api/addresses/txs`
> 
> Thanks, Isidoro
> 
> EDIT: I see right know the also the #27 is asking the same
