### ISSUE TITLE
Privacy analysis broken for transactions only paying miners

### ISSUE THREAD

**Issue by ysangkok** [Blockstream/esplora#95]
Example transaction: https://www.blockstream.info/tx/eb31ca1a4cbd97c2770983164d7560d2d03276ae1aee26f12d7c2c6424252f29

The privacy analysis notes "Likely self-transfer". But this transaction has no non-zero outputs, so it cannot be a self-transfer

Expected behaviour: Privacy analysis is not applicable on this transaction, and shouldn't be shown.

**Comment by shesek** [comment]
Fixed by https://github.com/Blockstream/esplora/commit/f15e38631adff0808e8a45d5fa72290a004c031e. Thanks for the report @ysangkok!
