### ISSUE TITLE
OP_CHECKSEQUENCEVERIFY is displayed as OP_NOP3

### ISSUE THREAD

**Issue by dooglus** [Blockstream/esplora#98]
OP_NOP3 was replaced with OP_CHECKSEQUENCEVERIFY when CSV activated but blockstream.info/tx/... displays OP_NOP3.

**Comment by shesek** [comment]
Thanks for the report! This is actually handled by the [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin) library, I opened [an issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/280) there.

**Comment by shesek** [comment]
Fixed in https://github.com/rust-bitcoin/rust-bitcoin/pull/282, will go live in esplora once this gets released in a new rust-bitcoin version.
